---

# *** Determine distro.

# Sets fact: zoidy_distrib_codename_
- name: Verify known Linux distro
  include_role:
    name: zoidy_apps_et_al
    tasks_from: all-init-suss-distro
    apply: { tags: "always" }
  tags:
    - app-virtualbox-apt

# ************************************************************************
# *** Apps. ***

- name: Load role to Install Chrome browser
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: app-chrome
    apply: { tags: "always" }
  tags: app-chrome

- name: Load role to Install Cinelerra-GG
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: app-cinelerra-gg
    apply: { tags: "always" }
  tags: app-cinelerra-gg

- name: Load role to Install Darktable
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: app-darktable
    apply: { tags: "always" }
  tags: app-darktable

- name: Load role to Install Digikam
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: app-digikam
    apply: { tags: "always" }
  tags: app-digikam

- name: Load role to Install OpenJUMP
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: app-openjump
    apply: { tags: "always" }
  tags: app-openjump

- name: Load role to Install Opera
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: app-opera
    apply: { tags: "always" }
  tags: app-opera

- name: "Load role to Install Pencil [Project]"
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: app-pencil-project-evolus
    apply: { tags: "always" }
  tags: app-pencil-project-evolus

- name: "Load role to Install Spotify"
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: app-spotify
    apply: { tags: "always" }
  tags: app-spotify

- name: "Load role to install VirtualBox using apt"
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: app-virtualbox-apt
    apply: { tags: "always" }
  tags: app-virtualbox-apt
  vars:
    zoidy_distrib_codename: "{{ zoidy_distrib_codename_ }}"

- name: "Load role to install VirtualBox from deb download"
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: app-virtualbox-deb
    apply: { tags: "always" }
  tags: app-virtualbox-deb
  vars:
    zoidy_distrib_codename: "{{ zoidy_distrib_codename_ }}"
  # ISOFF/2023-04-27: Prefer installing via apt.
  # - This task kept for posterity, just in case apt release ever
  #   lags behind apt release (which historically has happened, so).
  # OPTIN/2023-04-27: To support site.yml tag inheritence (e.g., `--tags
  # zoidy_apps_et_al`), use obtuse `when` test instead of 'never' tag.
  # - Use explicit `--tags app-virtualbox-deb` to run this task.
  when: "'app-virtualbox-deb' in ansible_run_tags"

- name: "Load role to install VirtualBox ExtPack from extpack download"
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: app-virtualbox-extpack
    apply: { tags: "always" }
  tags: app-virtualbox-extpack

# ************************************************************************
# *** Clis. ***

- name: Load role to Install ripgrep
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: cli-ripgrep
    apply: { tags: "always" }
  tags: cli-ripgrep

# ************************************************************************
# *** Dmns. ***

- name: Dropbox Daemon Installer
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: dmn-dropbox
    apply: { tags: "always" }
  tags: dmn-dropbox

# ************************************************************************
# *** Emai. ***

- name: Gmail Email Postfix setup
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: email-gmail-postfix
    apply: { tags: "always" }
  tags: email-gmail-postfix
  when: zoidy_homefries_postfix_fqdn != ''

# ************************************************************************
# *** Embbd Dev. ***

- name: Android Studio Installer
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: hardware-android-studio
    apply: { tags: "always" }
  tags: hardware-android-studio

- name: Arduino Platform Developer Installer
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: hardware-arduino
    apply: { tags: "always" }
  tags: hardware-arduino

# ************************************************************************
# *** Font 'ackch. ***

# 2023-04-26: This task for posterity; see zoidy_matecocido/tasks/font-hack-nerd-font
- name: Load role to Install Font “Hack” (aka Hack Classic; not “Hack Nerd Font”)
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: font-hack-classic
    apply: { tags: "always" }
  tags: font-hack-classic

- name: Load role to Install Fonts
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: font-mania
    apply: { tags: "always" }
  tags: font-mania

# ************************************************************************
# *** Glng apps. ***

- name: Load role to Install Go Lang Projects
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: golang-go-install-packages
    apply: { tags: "always" }
  tags: golang-go-install-packages

# ************************************************************************
# *** Melds. ***

- name: Load role to Configure Meld Preferences
  include_role:
    name: zoidy_apps_et_al
    tasks_from: meld-configure
    apply: { tags: "always" }
  tags: meld-configure

# ************************************************************************
# *** Node & Npms. ***

- name: Node.js npm Packages Installer
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: node-npm-packages
    apply: { tags: "always" }
  tags: node-npm-packages

# ************************************************************************
# *** Pips. ***

- name: Python Sources Installer
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: python-sources
    apply: { tags: "always" }
  tags: python-sources

# ************************************************************************
# *** Virt. ***

- name: Vagrant Installer
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: virt-vagrant
    apply: { tags: "always" }
  tags: virt-vagrant

