---

# ************************************************************************
# *** Prep tasks. ***

- name: SSH directory symlink populator
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: all-init-ssh-links
    apply: { tags: always }
  tags:
    # Ensures ~/.ssh setup before configuring GitHub SSH.
    - all-init-ssh-links
    #
    # Ensures GitHub SSH is setup, so 'repo' module clone works.
    - all-init-github-ssh
    # Let's you skip this task via `--skip-tags skip-github-ssh`.
    - skip-github-ssh
    #
    # Each of the following install tasks clone a GitHub repo using SSH.
    # - USYNC: GH_SSH_TASKS
    #
    - app-gimp-plugin-export-layers
    - app-gimp-plugin-wavelet-decompose
    - app-kdocker
    - cli-parT
    - golang-delve-debugger
    - vid-ttygif
  when: zoidy_homefries_ssh_root_dir != ''

- name: Run tasks to verify or configure GitHub SSH
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: all-init-github-ssh
    apply: { tags: always }
  tags:
    # Ensure GitHub SSH setup before running any super-task with a 'repo'
    # subtask that clones a GitHub repo (so clone uses user's GH key and
    # you can use git@github.com:user/repo URI).
    - all-init-github-ssh
    # A GH SSH prep skip tag, e.g.,
    #   `ansible-playbook ... --tag cli-parT --skip-tags skip-github-ssh`
    - skip-github-ssh
    #
    # Each of the following install tasks clone a GitHub repo using SSH.
    # - USYNC: GH_SSH_TASKS
    #
    - app-gimp-plugin-export-layers
    - app-gimp-plugin-wavelet-decompose
    - app-kdocker
    - cli-parT
    - golang-delve-debugger
    - vid-ttygif

# ************************************************************************
# *** GIMP. ***

- name: Load tasks to Install GIMP Export Layers Plug-in
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: app-gimp-plugin-export-layers
    apply: { tags: always }
  tags: app-gimp-plugin-export-layers

- name: Load tasks to Install GIMP Wavelet Decompose Plug-in
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: app-gimp-plugin-wavelet-decompose
    apply: { tags: always }
  tags: app-gimp-plugin-wavelet-decompose
  # OPTIN/2023-04-23: To support site.yml tag inheritence (e.g., `--tags
  # zoidy_apps_et_al`), use obtuse `when` test instead of 'never' tag.
  # - Use explicit `--tags app-gimp-...` to run this task.
  when: "'app-gimp-plugin-wavelet-decompose' in ansible_run_tags"


# ************************************************************************
# *** Gnucash. ***

- name: Load tasks to Install gnucash
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    # MAYBE/2020-11-14: Run these other dependent tasks before app-gnucash-build
    # (add app-gnucash-build to each of their apply-tags and tags):
    #    - app-gnucash-build
    #    - app-gnucash-conf
    #    - app-gnucash-docs
    #    - perl-finance-quote
    tasks_from: app-gnucash-build
    apply: { tags: always }
  tags:
    - all-gnucash
    #
    - app-gnucash-build

- name: Load tasks to Configure GnuCash
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: app-gnucash-conf
    apply: { tags: always }
  tags:
    - all-gnucash
    #
    - app-gnucash-conf

- name: Load tasks to Install gnucash docs
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: app-gnucash-docs
    apply: { tags: always }
  tags:
    - all-gnucash
    #
    - app-gnucash-docs

- name: Load tasks to Install Perl Finance::Quote
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: perl-finance-quote
    apply: { tags: always }
  tags:
    - all-gnucash
    #
    - perl-finance-quote

# ************************************************************************
# *** Glng apps. ***

- name: Load tasks to Install Delve
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: golang-delve-debugger
    apply: { tags: always }
  tags: golang-delve-debugger

# ************************************************************************
# *** Kdocker. ***

- name: Load tasks to Install Kdocker
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: app-kdocker
    apply: { tags: always }
  tags: app-kdocker
  # ISOFF/2023-04-24: KDocker opt-in; demoing apt version.
  # - MAYBE/2023-04-24: Remove task if apt version sufficient;
  #                     otherwise, remove 'when' test.
  # OPTIN/2023-04-24: To support site.yml tag inheritence (e.g., `--tags
  # zoidy_apps_et_al`), use obtuse `when` test instead of 'never' tag.
  # - Use explicit `--tags app-kdocker` to run this task.
  when: "'app-kdocker' in ansible_run_tags"

# ************************************************************************
# *** parT. ***

- name: parT Installer
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: cli-parT
    apply: { tags: always }
  tags: cli-parT

# ************************************************************************
# *** Tmux. ***

- name: Load tasks to clone-build-install tmux
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: app-tmux
    apply: { tags: always }
  tags: app-tmux

# ************************************************************************
# *** Vids. ***

- name: ttygif Installer
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: vid-ttygif
    apply: { tags: always }
  tags: vid-ttygif

