---

# *** Verify distro.

# REFER: https://linuxmint.com/download_all.php

# Linux Mint 21-21.3
- ansible.builtin.set_fact:
    zoidy_distrib_codename_: 'jammy'
  when: ansible_lsb.codename in ['vanessa', 'vera', 'victoria', 'virginia']

# Linux Mint 20-20.3
- ansible.builtin.set_fact:
    zoidy_distrib_codename_: 'focal'
  when: ansible_lsb.codename in ['ulyana', 'ulyssa', 'uma', 'una',]

# Linux Mint 19-19.3
- ansible.builtin.set_fact:
    zoidy_distrib_codename_: 'bionic'
  when: ansible_lsb.codename in ['tara', 'tessa', 'tina', 'tricia',]

- ansible.builtin.fail:
    msg: "Unexpected distro: “{{ ansible_facts.lsb.codename }}”"
  when: zoidy_distrib_codename_ is not defined

