# FUG
- name: SSH directory symlink populator
  include_role:
    name: zoidy_home-fries
    tasks_from: sec-ssh-symlinks
    apply:
      tags:
        - sec-ssh-symlinks
  tags:
    - sec-ssh-symlinks
    # Also ensure SSH setup if ensuring GH SSH setup.
    - init-github-ssh
    # Also ensure SSH if ensuring GH if running any task
    # with a repo: module that clones using user's GH key.
    - app-gimp-plugin-export-layers
    - app-gimp-plugin-wavelet-decompose
    - app-vim-brams
    - cli-cloc
    - cli-direnv
    - cli-parT
    - cli-reptile
    - cli-xrandr-invert-colors
    - golang-delve-debugger
    - python-chjson
    - vid-ttygif
  when: zoidy_homefries_ssh_root_dir != ''

- name: Run tasks to verify or configure GitHub SSH
  include_role:
    name: zoidy_home-fries
    tasks_from: init-github-ssh
    apply:
      tags:
        - init-github-ssh
  tags:
    - init-github-ssh
    # If running any task expecting GH key.
    - app-gimp-plugin-export-layers
    - app-gimp-plugin-wavelet-decompose
    - app-vim-brams
    - cli-cloc
    - cli-direnv
    - cli-parT
    - cli-reptile
    - cli-xrandr-invert-colors
    - golang-delve-debugger
    - python-chjson
    - vid-ttygif

# ************************************************************************
# *** Apps. ***

- name: Load role to Install GIMP Export Layers Plug-in
  include_role:
    name: zoidy_home-fries
    tasks_from: app-gimp-plugin-export-layers
    apply:
      tags:
        - app-gimp-plugin-export-layers
  tags: app-gimp-plugin-export-layers

- name: Load role to Install GIMP Wavelet Decompose Plug-in
  include_role:
    name: zoidy_home-fries
    tasks_from: app-gimp-plugin-wavelet-decompose
    apply:
      tags:
        - app-gimp-plugin-wavelet-decompose
  tags: app-gimp-plugin-wavelet-decompose

- name: Load role to Clone, Build, and Install Latest Vim
  include_role:
    name: zoidy_home-fries
    tasks_from: app-vim-brams
    apply:
      tags:
        - app-vim-brams
  tags: app-vim-brams

# ************************************************************************
# *** Clis. ***

- name: CLOC Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: cli-cloc
    apply:
      tags:
        - cli-cloc
  tags: cli-cloc

- name: Install Direnv Development Utility
  include_role:
    name: zoidy_home-fries
    tasks_from: cli-direnv
    apply:
      tags:
        - cli-direnv
  tags: cli-direnv

- name: parT Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: cli-parT
    apply:
      tags:
        - cli-parT
  tags: cli-parT

- name: Load role to Install reptile
  include_role:
    name: zoidy_home-fries
    tasks_from: cli-reptile
    apply:
      tags:
        - cli-reptile
  tags: cli-reptile

- name: Install Screen Color Inverter, i.e., Alert! Mechanism
  include_role:
    name: zoidy_home-fries
    tasks_from: cli-xrandr-invert-colors
    apply:
      tags:
        - cli-xrandr-invert-colors
  tags: cli-xrandr-invert-colors

# ************************************************************************
# *** Glng apps. ***

- name: Load role to Install Delve
  include_role:
    name: zoidy_home-fries
    tasks_from: golang-delve-debugger
    apply:
      tags:
        - golang-delve-debugger
  tags: golang-delve-debugger

# ************************************************************************
# *** Pycs. ***

- name: Python Chjson Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: python-chjson
    apply:
      tags:
        - python-chjson
  tags: python-chjson

# ************************************************************************
# *** Vids. ***

- name: ttygif Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: vid-ttygif
    apply:
      tags:
        - vid-ttygif
  tags: vid-ttygif

