---

# *** Ensure that Go is setup, for other tasks to use/rely upon.

# Don't install Go if already installed, or unless
# install-go task explicitly requested.
- ansible.builtin.set_fact:
    # USYNC: See also same GOLANG_VER in task dispatcher:
    #
    #   ~/.kit/ansible/roles/zoidy_apps_et_al/tasks/golang-install-go-lang.yml
    GOLANG_VER: '1.22.1'

- name: Check if Go installed
  ansible.builtin.shell: command -v go >/dev/null 2>&1
  register: go_exists
  ignore_errors: yes
  tags:
    # Tasks that rely on Go being available.
    - cli-ripgrep
    - golang-delve-debugger
    - golang-go-install-packages

# Prints, e.g.,
#   go version go1.20.3 linux/amd64
- name: Check Go version
  ansible.builtin.shell: go version | grep -q "go version go{{ GOLANG_VER }} "
  register: go_versioned
  when: go_exists.rc == 0
  tags:
    # Tasks that rely on Go being available.
    - cli-ripgrep
    - golang-delve-debugger
    - golang-go-install-packages

# ***

- name: Run task to Install Go Language (explicit)
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: golang-install-go-lang
    apply: { tags: always }
  tags:
    - all-init-go-lang
    #
    - golang-install-go-lang

- name: Run task to Install Go Language (implicit)
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: golang-install-go-lang
    apply: { tags: always }
  tags:
    # Tasks that rely on Go being available.
    - cli-ripgrep
    - golang-delve-debugger
    - golang-go-install-packages
    # When you run the role tag, don't run golang-install-go-lang twice.
    # - Note the using the 'never' tag won't work if your site.yml
    #   applies the role tagging when it loads the role.
    #   - I.e., this won't work:
    #       - never
    # - Instead, use the when conditional to check for an explicit
    #   task tag.
  when: >
    true
    and (go_exists.rc != 0 or go_versioned.rc != 0)
    and (false
      or 'cli-ripgrep' in ansible_run_tags
      or 'golang-delve-debugger' in ansible_run_tags
      or 'golang-go-install-packages' in ansible_run_tags
    )

