---

- name: SSH directory symlink populator
  include_role:
    name: zoidy_apps_et_al
    tasks_from: sec-ssh-symlinks
    apply: { tags: "always" }
  tags:
    - sec-ssh-symlinks
    # Also ensure SSH setup if ensuring GH SSH setup.
    - init-github-ssh
    # Let's you skip this task via `--skip-tags skip-github-ssh`.
    - skip-github-ssh
    # Also ensure SSH if ensuring GH if running any task
    # with a repo: module that clones using user's GH key.
    - app-gimp-plugin-export-layers
    - app-gimp-plugin-wavelet-decompose
    - cli-cloc
    - cli-direnv
    - cli-parT
    - golang-delve-debugger
    - python-chjson
    - vid-ttygif
  when: zoidy_homefries_ssh_root_dir != ''

- name: Run tasks to verify or configure GitHub SSH
  include_role:
    name: zoidy_apps_et_al
    tasks_from: init-github-ssh
    apply: { tags: "always" }
  tags:
    - init-github-ssh
    # Let's you skip this task via `--skip-tags skip-github-ssh`.
    - skip-github-ssh
    # If running any task expecting GH key.
    - app-gimp-plugin-export-layers
    - app-gimp-plugin-wavelet-decompose
    - cli-cloc
    - cli-direnv
    - cli-parT
    - golang-delve-debugger
    - python-chjson
    - vid-ttygif

# ************************************************************************
# *** Apps. ***

- name: Load role to Install GIMP Export Layers Plug-in
  include_role:
    name: zoidy_apps_et_al
    tasks_from: app-gimp-plugin-export-layers
    apply:
      tags:
        - app-gimp-plugin-export-layers
  tags: app-gimp-plugin-export-layers

- name: Load role to Install GIMP Wavelet Decompose Plug-in
  include_role:
    name: zoidy_apps_et_al
    tasks_from: app-gimp-plugin-wavelet-decompose
    apply:
      tags:
        - app-gimp-plugin-wavelet-decompose
  # OPTIN/2023-04-23: Use explicit --tag to run this task.
  #   tags: app-gimp-plugin-wavelet-decompose
  tags: never

# ************************************************************************
# *** Gnucash. ***

- name: Load role to Install gnucash
  include_role:
    name: zoidy_apps_et_al
    # MAYBE/2020-11-14: Run these other dependent tasks before app-gnucash-build
    # (add app-gnucash-build to each of their apply-tags and tags):
    #    - app-gnucash-build
    #    - app-gnucash-conf
    #    - app-gnucash-docs
    #    - perl-finance-quote
    tasks_from: app-gnucash-build
    apply:
      tags:
        - app-gnucash-build
        - all-gnucash
  tags:
    - app-gnucash-build
    - all-gnucash

- name: Load role to Configure GnuCash
  include_role:
    name: zoidy_apps_et_al
    tasks_from: app-gnucash-conf
    apply:
      tags:
        - app-gnucash-conf
        - all-gnucash
  tags:
    - app-gnucash-conf
    - all-gnucash

- name: Load role to Install gnucash docs
  include_role:
    name: zoidy_apps_et_al
    tasks_from: app-gnucash-docs
    apply:
      tags:
        - app-gnucash-docs
        - all-gnucash
  tags:
    - app-gnucash-docs
    - all-gnucash

- name: Load role to Install Perl Finance::Quote
  include_role:
    name: zoidy_apps_et_al
    tasks_from: perl-finance-quote
    apply:
      tags:
        - perl-finance-quote
        - all-gnucash
  tags:
    - perl-finance-quote
    - all-gnucash

# ************************************************************************
# *** Tmux. ***

- name: Load role to install libevent
  include_role:
    name: zoidy_apps_et_al
    tasks_from: lib-libevent
    apply:
      tags:
        - lib-libevent
  tags: lib-libevent

- name: Load role to install ncurses
  include_role:
    name: zoidy_apps_et_al
    tasks_from: lib-ncurses
    apply:
      tags:
        - lib-ncurses
  tags: lib-ncurses

- name: Load role to Clone, Build, and Install tmux
  include_role:
    name: zoidy_apps_et_al
    tasks_from: app-tmux
    apply:
      tags:
        - app-tmux
  tags: app-tmux

# ************************************************************************
# *** Clis. ***

- name: CLOC Installer
  include_role:
    name: zoidy_apps_et_al
    tasks_from: cli-cloc
    apply:
      tags:
        - cli-cloc
  tags: cli-cloc

- name: Install Direnv Development Utility
  include_role:
    name: zoidy_apps_et_al
    tasks_from: cli-direnv
    apply:
      tags:
        - cli-direnv
  tags: cli-direnv

- name: parT Installer
  include_role:
    name: zoidy_apps_et_al
    tasks_from: cli-parT
    apply:
      tags:
        - cli-parT
  tags: cli-parT

# ************************************************************************
# *** Glng apps. ***

- name: Load role to Install Delve
  include_role:
    name: zoidy_apps_et_al
    tasks_from: golang-delve-debugger
    apply:
      tags:
        - golang-delve-debugger
  tags: golang-delve-debugger

# ************************************************************************
# *** Pycs. ***

- name: Python Chjson Installer
  include_role:
    name: zoidy_apps_et_al
    tasks_from: python-chjson
    apply:
      tags:
        - python-chjson
  tags: python-chjson

# ************************************************************************
# *** Vids. ***

- name: ttygif Installer
  include_role:
    name: zoidy_apps_et_al
    tasks_from: vid-ttygif
    apply:
      tags:
        - vid-ttygif
  tags: vid-ttygif

