---

# ************************************************************************
# *** Go Lang. ***

# Dubs Vim: Set up Go Lang, for RipGrep and `tags` command
- name: Load role to Install Go Language
  include_role:
    name: zoidy_home-fries
    tasks_from: golang-go-lang
    apply:
      tags:
        - golang-go-lang
  tags: golang-go-lang, dubs-vim, cli-direnv, cli-ripgrep

# ************************************************************************
# *** Apps. ***

- name: Load role to Install Chrome browser
  include_role:
    name: zoidy_home-fries
    tasks_from: app-chrome
    apply:
      tags:
        - app-chrome
  tags: app-chrome

- name: Load role to Install Darktable
  include_role:
    name: zoidy_home-fries
    tasks_from: app-darktable
    apply:
      tags:
        - app-darktable
  vars:
    zoidy_distrib_codename: "{{ zoidy_distrib_codename_ }}"
  tags: app-darktable

- name: Load role to Install Digikam
  include_role:
    name: zoidy_home-fries
    tasks_from: app-digikam
    apply:
      tags:
        - app-digikam
  tags: app-digikam

- name: Load role to Fix Firefox Click-Scrolling Behavior
  include_role:
    name: zoidy_home-fries
    tasks_from: app-firefox-fix_scroll
    apply:
      tags:
        - app-firefox-fix_scroll
  tags: app-firefox-fix_scroll

- name: Load role to Install GIMP docs
  include_role:
    name: zoidy_home-fries
    tasks_from: app-gimp-docs
    apply:
      tags:
        - app-gimp-docs
  tags: app-gimp-docs

- name: Load role to Install GIMP Export Layers Plug-in
  include_role:
    name: zoidy_home-fries
    tasks_from: app-gimp-plugin-export-layers
    apply:
      tags:
        - app-gimp-plugin-export-layers
  tags: app-gimp-plugin-export-layers

- name: Load role to Install Google Earth
  include_role:
    name: zoidy_home-fries
    tasks_from: app-google-earth
    apply:
      tags:
        - app-google-earth
  tags: app-google-earth

- name: Load role to Install OpenJUMP
  include_role:
    name: zoidy_home-fries
    tasks_from: app-openjump
    apply:
      tags:
        - app-openjump
  tags: app-openjump

- name: Load role to Install Opera
  include_role:
    name: zoidy_home-fries
    tasks_from: app-opera
    apply:
      tags:
        - app-opera
  tags: app-opera

- name: "Load role to Install Pencil [Project]"
  include_role:
    name: zoidy_home-fries
    tasks_from: app-pencil-project-evolus
    apply:
      tags:
        - app-pencil-project-evolus
  tags: app-pencil-project-evolus

# Dubs Vim: Install gVim to enable the Dubs Vim you already put in home.
- name: Load role to Clone, Build, and Install Latest Vim
  include_role:
    name: zoidy_home-fries
    tasks_from: app-vim-brams
    apply:
      tags:
        - app-vim-brams
  tags: app-vim-brams, dubs-vim

- name: Load role to Download, Get Setup, and Install VirtualBox
  include_role:
    name: zoidy_home-fries
    tasks_from: app-virtualbox
    apply:
      tags:
        - app-virtualbox
  vars:
    zoidy_distrib_codename: "{{ zoidy_distrib_codename_ }}"
  tags: app-virtualbox

# ************************************************************************
# *** Clis. ***

- name: CLOC Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: cli-cloc
    apply:
      tags:
        - cli-cloc
  tags: cli-cloc

- name: Install Direnv Development Utility
  include_role:
    name: zoidy_home-fries
    tasks_from: cli-direnv
    apply:
      tags:
        - cli-direnv
  tags: cli-direnv

# A Disabled Task [that I should just delete?].
- name: Load role to Enable Git Large File Storage
  include_role:
    name: zoidy_home-fries
    tasks_from: cli-git-lfs
    apply:
      tags:
        - cli-git-lfs
  tags: cli-git-lfs
  # 2018-12-23: On second thought, git-lfs still clones latest version
  # locally, so does not work as I hoped; can use symlink repo instead.
  when: False

- name: OptiPNG Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: cli-optipng
    apply:
      tags:
        - cli-optipng
  tags: cli-optipng

- name: parT Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: cli-parT
    apply:
      tags:
        - cli-parT
  tags: cli-parT

- name: Load role to Install reptile
  include_role:
    name: zoidy_home-fries
    tasks_from: cli-reptile
    apply:
      tags:
        - cli-reptile
  tags: cli-reptile

- name: Load role to Install reptile keybindings
  include_role:
    name: zoidy_home-fries
    tasks_from: cli-reptile-keybindings
    apply:
      tags:
        - cli-reptile-keybindings
        - reset-keybindings
  tags: cli-reptile-keybindings, reset-keybindings

# Dubs Vim: is pointless without getting Ripped first.
- name: Load role to Install ripgrep
  include_role:
    name: zoidy_home-fries
    tasks_from: cli-ripgrep
    apply:
      tags:
        - cli-ripgrep
  tags: cli-ripgrep, dubs-vim

- name: Install Screen Color Inverter, i.e., Alert! Mechanism
  include_role:
    name: zoidy_home-fries
    tasks_from: cli-xrandr-invert-colors
    apply:
      tags:
        - cli-xrandr-invert-colors
  tags: cli-xrandr-invert-colors

# ************************************************************************
# *** Devr. ***

- name: Hamster Dob/Nark Development Environment Setup
  include_role:
    name: zoidy_home-fries
    tasks_from: dev-hamster-dob-nark
    apply:
      tags:
        - dev-hamster-dob-nark
  tags: dev-hamster-dob-nark

# ************************************************************************
# *** Dmns. ***

- name: Dropbox Daemon Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: dmn-dropbox
    apply:
      tags:
        - dmn-dropbox
  tags: dmn-dropbox

# ************************************************************************
# *** Font 'ackch. ***

# Dubs Vim: Install Hack Font
- name: Load role to Install Font "Hack"
  include_role:
    name: zoidy_home-fries
    tasks_from: font-hack
    apply:
      tags:
        - font-hack
  tags: font-hack, dubs-vim

- name: Load role to Install Fonts
  include_role:
    name: zoidy_home-fries
    tasks_from: font-mania
    apply:
      tags:
        - font-mania
  tags: font-mania

# ************************************************************************
# *** Glng apps. ***

- name: Load role to Install Delve
  include_role:
    name: zoidy_home-fries
    tasks_from: golang-delve-debugger
    apply:
      tags:
        - golang-delve-debugger
  tags: golang-delve-debugger

- name: Load role to Install Go Lang Projects
  include_role:
    name: zoidy_home-fries
    tasks_from: golang-go-get-packages
    apply:
      tags:
        - golang-go-get-packages
  tags: golang-go-get-packages

# ************************************************************************
# *** Pltfs. ***

- name: Android Studio Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: hardware-android-studio
    apply:
      tags:
        - hardware-android-studio
  tags: hardware-android-studio

- name: Arduino Platform Developer Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: hardware-arduino
    apply:
      tags:
        - hardware-arduino
  tags: hardware-arduino

# ************************************************************************
# *** Npms. ***

- name: Node.js npm Package Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: node-npm-packages
    apply:
      tags:
        - node-npm-packages
  tags: node-npm-packages

- name: Node.js nvm Version Manager Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: node-nvm-version-mgr
    apply:
      tags:
        - node-nvm-version-mgr
  tags: node-nvm-version-mgr

- name: Install various Node.js versions using nvm
  include_role:
    name: zoidy_home-fries
    tasks_from: node-nvm-versions
    apply:
      tags:
        - node-nvm-versions
  tags: node-nvm-versions

# ************************************************************************
# *** Pips. ***

- name: Python PIPs Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: python-pip-packages
    apply:
      tags:
        - python-pip-packages
  tags: python-pip-packages

- name: Python Sources Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: python-sources
    apply:
      tags:
        - python-sources
  tags: python-sources

# ************************************************************************
# *** Pycs. ***

- name: Python Chjson Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: python-chjson
    apply:
      tags:
        - python-chjson
  tags: python-chjson

# ************************************************************************
# *** Refs. ***

- name: Webster Dictionary Fetcher
  include_role:
    name: zoidy_home-fries
    tasks_from: ref-dictionary
    apply:
      tags:
        - ref-dictionary
  tags: ref-dictionary

# ************************************************************************
# *** Rbys. ***

- name: Ruby-Install Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: ruby-install-base
    apply:
      tags:
        - ruby-install-base
  tags: ruby-install-base

- name: Ruby-Install Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: ruby-install-chruby
    apply:
      tags:
        - ruby-install-chruby
  tags: ruby-install-chruby

- name: Ruby Gems Package Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: ruby-install-versions
    apply:
      tags:
        - ruby-install-versions
  tags: ruby-install-versions

- name: Ruby Gems Package Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: ruby-rubygems-packages
    apply:
      tags:
        - ruby-rubygems-packages
  tags: ruby-rubygems-packages

# ************************************************************************
# *** Secs. ***

- name: Pass Store Tomb Plugin Extenstion Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: sec-pass-plug-tomb
    apply:
      tags:
        - sec-pass-plug-tomb
  tags: sec-pass-plug-tomb

# ************************************************************************
# *** Vids. ***

- name: ttygif Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: vid-ttygif
    apply:
      tags:
        - vid-ttygif
  tags: vid-ttygif

# ************************************************************************
# *** Virt. ***

- name: Vagrant Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: virt-vagrant
    apply:
      tags:
        - virt-vagrant
  tags: virt-vagrant

