---

# ************************************************************************
# *** Apps. ***

- name: Load role to Install Chrome browser
  include_role:
    name: zoidy_apps_et_al
    tasks_from: app-chrome
    apply:
      tags:
        - app-chrome
  tags: app-chrome

- name: Load role to Install Cinelerra-GG
  include_role:
    name: zoidy_apps_et_al
    tasks_from: app-cinelerra-gg
    apply:
      tags:
        - app-cinelerra-gg
  tags: app-cinelerra-gg

- name: Load role to Install Darktable
  include_role:
    name: zoidy_apps_et_al
    tasks_from: app-darktable
    apply:
      tags:
        - app-darktable
  vars:
    zoidy_distrib_codename: "{{ zoidy_distrib_codename_ }}"
  tags: app-darktable

- name: Load role to Install Digikam
  include_role:
    name: zoidy_apps_et_al
    tasks_from: app-digikam
    apply:
      tags:
        - app-digikam
  tags: app-digikam

- name: Load role to Install Kdocker
  include_role:
    name: zoidy_apps_et_al
    tasks_from: app-kdocker
    apply:
      tags:
        - app-kdocker
  tags: app-kdocker

- name: Load role to Install OpenJUMP
  include_role:
    name: zoidy_apps_et_al
    tasks_from: app-openjump
    apply:
      tags:
        - app-openjump
  tags: app-openjump

- name: Load role to Install Opera
  include_role:
    name: zoidy_apps_et_al
    tasks_from: app-opera
    apply:
      tags:
        - app-opera
  tags: app-opera

- name: "Load role to Install Pencil [Project]"
  include_role:
    name: zoidy_apps_et_al
    tasks_from: app-pencil-project-evolus
    apply:
      tags:
        - app-pencil-project-evolus
  tags: app-pencil-project-evolus

- name: "Load role to Install Spotify"
  include_role:
    name: zoidy_apps_et_al
    tasks_from: app-spotify
    apply:
      tags:
        - app-spotify
  tags: app-spotify

- name: "Load role to Install VirtualBox"
  include_role:
    name: zoidy_apps_et_al
    tasks_from: app-virtualbox
    apply:
      tags:
        - app-virtualbox
  tags: app-virtualbox

# ************************************************************************
# *** Clis. ***

- name: Load role to Install ripgrep
  include_role:
    name: zoidy_apps_et_al
    tasks_from: cli-ripgrep
    apply:
      tags:
        - cli-ripgrep
  tags: cli-ripgrep

# ************************************************************************
# *** Dmns. ***

- name: Dropbox Daemon Installer
  include_role:
    name: zoidy_apps_et_al
    tasks_from: dmn-dropbox
    apply:
      tags:
        - dmn-dropbox
  tags: dmn-dropbox

# ************************************************************************
# *** Emai. ***

- name: Gmail Email Postfix setup
  include_role:
    name: zoidy_apps_et_al
    tasks_from: email-gmail-postfix
    apply:
      tags:
        - email-gmail-postfix
  tags: email-gmail-postfix
  when: zoidy_homefries_postfix_fqdn != ''

# ************************************************************************
# *** Font 'ackch. ***

- name: Load role to Install Font “Hack”
  include_role:
    name: zoidy_apps_et_al
    tasks_from: font-hack
    apply:
      tags:
        - font-hack
  tags: font-hack, dubs-vim

- name: Load role to Install Font “Hack Nerd Font”
  include_role:
    name: zoidy_apps_et_al
    tasks_from: font-hack-nerd-font
    apply:
      tags:
        - font-hack-nerd-font
  tags: font-hack-nerd-font

- name: Load role to Install Fonts
  include_role:
    name: zoidy_apps_et_al
    tasks_from: font-mania
    apply:
      tags:
        - font-mania
  tags: font-mania

# ************************************************************************
# *** Glng apps. ***

- name: Load role to Install Go Lang Projects
  include_role:
    name: zoidy_apps_et_al
    tasks_from: golang-go-install-packages
    apply:
      tags:
        - golang-go-install-packages
  tags: golang-go-install-packages

# ************************************************************************
# *** Pltfs. ***

- name: Android Studio Installer
  include_role:
    name: zoidy_apps_et_al
    tasks_from: hardware-android-studio
    apply:
      tags:
        - hardware-android-studio
  tags: hardware-android-studio

- name: Arduino Platform Developer Installer
  include_role:
    name: zoidy_apps_et_al
    tasks_from: hardware-arduino
    apply:
      tags:
        - hardware-arduino
  tags: hardware-arduino

# ************************************************************************
# *** Npms. ***

- name: Node.js node Installer
  include_role:
    name: zoidy_apps_et_al
    tasks_from: node-npmjs-install
    apply:
      tags:
        - node-npmjs-install
  tags: node-npmjs-install

- name: Node.js npm Installer
  include_role:
    name: zoidy_apps_et_al
    tasks_from: node-node-install
    apply:
      tags:
        - node-node-install
  tags: node-node-install

- name: Node.js npm Packages Installer
  include_role:
    name: zoidy_apps_et_al
    tasks_from: node-npm-packages
    apply:
      tags:
        - node-npm-packages
  tags: node-npm-packages

- name: Node.js nvm Version Manager Installer
  include_role:
    name: zoidy_apps_et_al
    tasks_from: node-nvm-version-mgr
    apply:
      tags:
        - node-nvm-version-mgr
  tags: node-nvm-version-mgr

- name: Install various Node.js versions using nvm
  include_role:
    name: zoidy_apps_et_al
    tasks_from: node-nvm-versions
    apply:
      tags:
        - node-nvm-versions
  tags: node-nvm-versions

# ************************************************************************
# *** Pips. ***

- name: Python Sources Installer
  include_role:
    name: zoidy_apps_et_al
    tasks_from: python-sources
    apply:
      tags:
        - python-sources
  tags: python-sources

# ************************************************************************
# *** Refs. ***

- name: Webster Dictionary Fetcher
  include_role:
    name: zoidy_apps_et_al
    tasks_from: ref-dictionary
    apply:
      tags:
        - ref-dictionary
  tags: ref-dictionary

# ************************************************************************
# *** Virt. ***

- name: Vagrant Installer
  include_role:
    name: zoidy_apps_et_al
    tasks_from: virt-vagrant
    apply:
      tags:
        - virt-vagrant
  tags: virt-vagrant

