---

# *** Verify distro.

- set_fact:
    zoidy_distrib_codename_: 'bionic'
  when: ansible_lsb.codename == 'tara'
  tags: always

- fail: msg="Unexpected distro∷ “{{ ansible_facts.lsb.codename }}”"
  when: zoidy_distrib_codename_ is not defined
  tags: always

# *** Task Setup (Ensures-Dirs)

- name: Ensure ~/.downloads directory exists
  file: path={{ zoidy_homefries_downloads_dir }} state=directory
  tags: always

- name: Ensure ~/.downloads/fonts directory exists
  file: path={{ zoidy_homefries_dls_fonts_dir }} state=directory
  tags: always

- name: Ensure ~/.local directory exists
  file: path="{{ zoidy_homefries_user_local_dir }}" state=directory
  tags: always

- name: Ensure ~/.local/bin directory exists
  file: path="{{ zoidy_homefries_user_local_bin_dir }}" state=directory
  tags: always

- name: Ensure ~/.local/docs directory exists
  file: path="{{ zoidy_homefries_user_docs_dir }}" state=directory
  tags: always

# ***

- name: Load role to run first task wave
  include_role:
    name: zoidy_home-fries
    tasks_from: all-first
    apply:
      tags:
        - all-first
  tags: all-first, always

- name: Load role to run final task wave
  include_role:
    name: zoidy_home-fries
    tasks_from: all-tasks
    apply:
      tags:
        - all-tasks
  tags: all-tasks, always

