---

# *** Task Setup (Ensures-Dirs)

- name: Ensure opt-downloads directory exists
  file: path={{ zoidy_homefries_downloads_dir }} state=directory
  tags: always

- name: Ensure user ~/.local/bin directory exists
  file: path="{{ ansible_env.HOME }}/.local/bin" state=directory
  tags: always

# *** Install Hack Font

- name: Load role to Install Font "Hack"
  include_role:
    name: zoidy_home-fries
    tasks_from: font-hack-install
    apply:
      tags:
        - font-hack-install
  tags: font-hack-install

# *** Go Lang Tasks

- name: Load role to Install Go Language
  include_role:
    name: zoidy_home-fries
    tasks_from: go-lang-install
    apply:
      tags:
        - go-lang-install
  tags: go-lang-install

- name: Load role to Install ripgrep
  include_role:
    name: zoidy_home-fries
    tasks_from: ripgrep-install
    apply:
      tags:
        - ripgrep-install
  tags: ripgrep-install

# *** Disabled Tasks [that I should just delete?]

- name: Load role to Enable Git Large File Storage
  include_role:
    name: zoidy_home-fries
    tasks_from: git-lfs-package-install
    apply:
      tags:
        - git-lfs-package-install
  tags: git-lfs-package-install
  # 2018-12-23: On second thought, git-lfs still clones latest version
  # locally, so does not work as I hoped; can use symlink repo instead.
  when: False

# *** Other Tasks

- name: Load role to Install Chrome browser
  include_role:
    name: zoidy_home-fries
    tasks_from: chrome-install
    apply:
      tags:
        - chrome-install
  tags: chrome-install

- name: Load role to Download, Get Setup, and Install VirtualBox
  include_role:
    name: zoidy_home-fries
    tasks_from: virtualbox-deb-install
    apply:
      tags:
        - virtualbox-deb-install
  tags: virtualbox-deb-install

- name: Load role to Install Digikam
  include_role:
    name: zoidy_home-fries
    tasks_from: digikam-appimage
    apply:
      tags:
        - digikam-appimage
  tags: digikam-appimage

- name: Load role to Clone, Build, and Install Latest Vim
  include_role:
    name: zoidy_home-fries
    tasks_from: brams-vim-make-install
    apply:
      tags:
        - brams-vim-make-install
  tags: brams-vim-make-install

- name: Install Screen Color Inverter, i.e., Alert! Mechanism
  include_role:
    name: zoidy_home-fries
    tasks_from: xrandr-invert-colors
    apply:
      tags:
        - xrandr-invert-colors
  tags: xrandr-invert-colors

- name: NPM Package Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: npm-packages-install
    apply:
      tags:
        - npm-packages-install
  tags: npm-packages-install

- name: Install Direnv Development Utility
  include_role:
    name: zoidy_home-fries
    tasks_from: direnv-install
    apply:
      tags:
        - direnv-install
  tags: direnv-install

- name: Ruby-Install Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: ruby-install-install
    apply:
      tags:
        - ruby-install-install
  tags: ruby-install-install

- name: Ruby-Install Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: ruby-chruby-install
    apply:
      tags:
        - ruby-chruby-install
  tags: ruby-chruby-install

- name: Ruby Gems Package Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: ruby-versions-install
    apply:
      tags:
        - ruby-versions-install
  tags: ruby-versions-install

- name: Ruby Gems Package Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: ruby-gems-install
    apply:
      tags:
        - ruby-gems-install
  tags: ruby-gems-install

