---

# *** Verify distro.

# Sets fact: zoidy_distrib_codename_
- name: Verify known Linux distro
  include_role:
    name: zoidy_apps_et_al
    tasks_from: all-init-suss-distro
    apply: { tags: "always" }
  tags:
    - python-deadsnakes

# *** Task Setup (Ensures-Dirs)

# Ensures dirs: ~/.downloads, ~/.local/, etc.
- name: Ensure target directories exist
  include_role:
    name: zoidy_apps_et_al
    tasks_from: all-init-ensure-dirs
  tags: always

# ***

- name: Run tasks to ensure Go is good to go
  include_role:
    name: zoidy_apps_et_al
    tasks_from: init-go-lang
    apply: { tags: "always" }
  tags:
    - all-github
    - cli-direnv
    - cli-ripgrep
    - golang-delve-debugger
    - golang-go-install-packages
    - golang-go-lang
    - init-go-lang

- name: Run tasks related to GitHub SSH
  include_role:
    name: zoidy_apps_et_al
    tasks_from: all-github
  tags:
    - all-github
    # If ensuring SSH ready.
    - sec-ssh-symlinks
    # If ensuring GH SSH present.
    - init-github-ssh
    #
    # If running any task expecting GH key.
    #
    - app-gimp-plugin-export-layers
    - app-gimp-plugin-wavelet-decompose
    - cli-cloc
    - cli-direnv
    - cli-parT
    - golang-delve-debugger
    - python-chjson
    - vid-ttygif
    # tmux et al.
    - lib-libevent
    - lib-ncurses
    - app-tmux
    # gnucash
    - app-gnucash-build
    - app-gnucash-conf
    - app-gnucash-docs
    - perl-finance-quote

- name: Load all-tasks dispatcher
  include_role:
    name: zoidy_apps_et_al
    tasks_from: all-tasks
    apply:
      tags:
        - all-tasks
  tags: all-tasks, always

