---

# *** Verify distro.

- set_fact:
    zoidy_distrib_codename_: 'bionic'
  when: ansible_lsb.codename in ['tara', 'tessa', 'tricia',]
  tags: always

- fail: msg="Unexpected distro∷ “{{ ansible_facts.lsb.codename }}”"
  when: zoidy_distrib_codename_ is not defined
  tags: always

# *** Task Setup (Ensures-Dirs)

- name: Ensure ~/.downloads directory exists
  file: path={{ zoidy_homefries_downloads_dir }} state=directory
  tags: always

- name: Ensure ~/.downloads/fonts directory exists
  file: path={{ zoidy_homefries_dls_fonts_dir }} state=directory
  tags: always

- name: Ensure ~/.local directory exists
  file: path="{{ zoidy_homefries_user_local_dir }}" state=directory
  tags: always

- name: Ensure ~/.local/bin directory exists
  file: path="{{ zoidy_homefries_user_local_bin_dir }}" state=directory
  tags: always

- name: Ensure ~/.local/docs directory exists
  file: path="{{ zoidy_homefries_user_docs_dir }}" state=directory
  tags: always

# ***

- name: Run tasks to ensure Go is good to go
  include_role:
    name: zoidy_home-fries
    tasks_from: init-go-lang
    apply:
      tags:
        - init-go-lang
  tags: init-go-lang, always

- name: Run tasks related to GitHub SSH
  include_role:
    name: zoidy_home-fries
    tasks_from: all-github
  # We could simplify this and specify not all the tags, e.g.,
  #   tags: all-github, always
  # but then the task name will always appear in any play.
  tags:
    - all-github
    # If ensuring SSH ready.
    - sec-ssh-symlinks
    # If ensuring GH SSH present.
    - init-github-ssh
    # If running any task expecting GH key.
    - app-gimp-plugin-export-layers
    - app-gimp-plugin-wavelet-decompose
    - app-vim-brams
    - cli-cloc
    - cli-direnv
    - cli-parT
    - cli-reptile
    - cli-xrandr-invert-colors
    - golang-delve-debugger
    - python-chjson
    - vid-ttygif
    # tmux et al.
    - lib-libevent
    - lib-ncurses
    - app-tmux
    # gnucash
    - lib-gettext
    - app-gnucash
    - app-gnucash-docs

- name: Run all the tasks to do all the things
  include_role:
    name: zoidy_home-fries
    tasks_from: all-tasks
    apply:
      tags:
        - all-tasks
  tags: all-tasks, always

