---

# *** Task Setup (Ensures-Dirs)

- name: Ensure opt-downloads directory exists
  file: path={{ zoidy_homefries_downloads_dir }} state=directory
  tags: always

- name: Ensure user ~/.local/bin directory exists
  file: path="{{ ansible_env.HOME }}/.local/bin" state=directory
  tags: always

# *** Package Installers

# ************************************************************************
# *** Dubs Vim. ***

# **** Install Hack Font

- name: Load role to Install Font "Hack"
  include_role:
    name: zoidy_home-fries
    tasks_from: font-hack
    apply:
      tags:
        - font-hack
  tags: font-hack

# **** Set up Go Lang, for RipGrep and `tags` command

- name: Load role to Install Go Language
  include_role:
    name: zoidy_home-fries
    tasks_from: golang-go-lang
    apply:
      tags:
        - golang-go-lang
  tags: golang-go-lang

# **** Dubs is pointless without getting Ripped first

- name: Load role to Install ripgrep
  include_role:
    name: zoidy_home-fries
    tasks_from: cli-ripgrep
    apply:
      tags:
        - cli-ripgrep
  tags: cli-ripgrep

# **** Install gVim to enable the Dubs Vim you already put in home

- name: Load role to Clone, Build, and Install Latest Vim
  include_role:
    name: zoidy_home-fries
    tasks_from: app-vim-brams
    apply:
      tags:
        - app-vim-brams
  tags: app-vim-brams

# ************************************************************************
# *** Apps. ***

- name: Load role to Install Chrome browser
  include_role:
    name: zoidy_home-fries
    tasks_from: app-chrome
    apply:
      tags:
        - app-chrome
  tags: app-chrome

- name: Load role to Install Digikam
  include_role:
    name: zoidy_home-fries
    tasks_from: app-digikam
    apply:
      tags:
        - app-digikam
  tags: app-digikam

- name: Load role to Download, Get Setup, and Install VirtualBox
  include_role:
    name: zoidy_home-fries
    tasks_from: app-virtualbox
    apply:
      tags:
        - app-virtualbox
  tags: app-virtualbox

# ************************************************************************
# *** Clis. ***

- name: CLOC Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: cli-cloc
    apply:
      tags:
        - cli-cloc
  tags: cli-cloc

- name: Install Direnv Development Utility
  include_role:
    name: zoidy_home-fries
    tasks_from: cli-direnv
    apply:
      tags:
        - cli-direnv
  tags: cli-direnv

# A Disabled Task [that I should just delete?].
- name: Load role to Enable Git Large File Storage
  include_role:
    name: zoidy_home-fries
    tasks_from: cli-git-lfs
    apply:
      tags:
        - cli-git-lfs
  tags: cli-git-lfs
  # 2018-12-23: On second thought, git-lfs still clones latest version
  # locally, so does not work as I hoped; can use symlink repo instead.
  when: False

- name: parT Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: cli-parT
    apply:
      tags:
        - cli-parT
  tags: cli-parT

- name: Install Screen Color Inverter, i.e., Alert! Mechanism
  include_role:
    name: zoidy_home-fries
    tasks_from: cli-xrandr-invert-colors
    apply:
      tags:
        - cli-xrandr-invert-colors
  tags: cli-xrandr-invert-colors

# ************************************************************************
# *** Dmns. ***

- name: Dropbox Daemon Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: dmn-dropbox
    apply:
      tags:
        - dmn-dropbox
  tags: dmn-dropbox

# ************************************************************************
# *** Npms. ***

- name: NPM Package Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: node-npm-packages
    apply:
      tags:
        - node-npm-packages
  tags: node-npm-packages

# ************************************************************************
# *** Pips. ***

- name: Python PIPs Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: python-pip-packages
    apply:
      tags:
        - python-pip-packages
  tags: python-pip-packages

# ************************************************************************
# *** Rbys. ***

- name: Ruby-Install Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: ruby-install-base
    apply:
      tags:
        - ruby-install-base
  tags: ruby-install-base

- name: Ruby-Install Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: ruby-install-chruby
    apply:
      tags:
        - ruby-install-chruby
  tags: ruby-install-chruby

- name: Ruby Gems Package Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: ruby-install-versions
    apply:
      tags:
        - ruby-install-versions
  tags: ruby-install-versions

- name: Ruby Gems Package Installer
  include_role:
    name: zoidy_home-fries
    tasks_from: ruby-rubygems-packages
    apply:
      tags:
        - ruby-rubygems-packages
  tags: ruby-rubygems-packages

