---

# *** Verify distro.

# Sets fact: zoidy_distrib_codename_
- name: Verify known Linux distro
  include_role:
    name: zoidy_apps_et_al
    tasks_from: all-init-suss-distro
    apply: { tags: "always" }
  tags:
    - app-scala-sbt
    - python-deadsnakes

# *** Task Setup (Ensures-Dirs)

# Ensures dirs: ~/.downloads, ~/.local/, etc.
- name: Ensure target directories exist
  include_role:
    name: zoidy_apps_et_al
    tasks_from: all-init-ensure-dirs
  tags: always

# ***

- name: Run tasks to ensure Go is good to go
  include_role:
    name: zoidy_apps_et_al
    tasks_from: init-go-lang
    apply:
      tags:
        - init-go-lang
  tags: init-go-lang, always

- name: Run tasks related to GitHub SSH
  include_role:
    name: zoidy_apps_et_al
    tasks_from: all-github
  # We could simplify this and specify not all the tags, e.g.,
  #   tags: all-github, always
  # but then the task name will always appear in any play.
  tags:
    - all-github
    # If ensuring SSH ready.
    - sec-ssh-symlinks
    # If ensuring GH SSH present.
    - init-github-ssh
    #
    # If running any task expecting GH key.
    #
    - app-gimp-plugin-export-layers
    - app-gimp-plugin-wavelet-decompose
    - cli-cloc
    - cli-direnv
    - cli-parT
    - golang-delve-debugger
    - python-chjson
    - vid-ttygif
    # tmux et al.
    - lib-libevent
    - lib-ncurses
    - app-tmux
    # gnucash
    - lib-gettext
    - lib-libboost
    - app-gnucash
    - app-gnucash-docs
    - perl-finance-quote

- name: Run all the tasks to do all the things
  include_role:
    name: zoidy_apps_et_al
    tasks_from: all-tasks
    apply:
      tags:
        - all-tasks
  tags: all-tasks, always

