---

# *** Task Setup (Ensures-Dirs)

# Ensures dirs: ~/.downloads, ~/.local/, etc.
- name: Load dispatcher » Ensure target directories exist
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: all-init-ensure-dirs
  tags: always

# ***

- name: Load dispatcher » Install Go Language
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: all-init-go-lang
  tags: always

- name: Run tasks that use sources obtained via GitHub SSH
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: all-github
  tags:
    - all-github
    # If ensuring SSH ready.
    - all-init-ssh-links
    # If ensuring GH SSH present.
    - all-init-github-ssh
    # The go tasks rely on GH repos.
    - all-init-go-lang
    #
    # Each of the following install tasks clone a GitHub repo using SSH.
    # - USYNC: GH_SSH_TASKS
    #
    # *** One-offs
    - app-kdocker
    - cli-parT
    - golang-delve-debugger
    - vid-ttygif
    #
    # *** GIMP
    - app-gimp-plugin-export-layers
    - app-gimp-plugin-wavelet-decompose
    #
    # *** gnucash
    - app-gnucash-build
    - app-gnucash-conf
    - app-gnucash-docs
    - perl-finance-quote
    #
    # *** tmux
    - app-tmux

- name: Load all-tasks dispatcher
  ansible.builtin.include_role:
    name: zoidy_apps_et_al
    tasks_from: all-tasks
  tags:
    # Tasks in the all-tasks file use their own tag matches, so we could
    # use always here:
    #  - always
    # but using a list lets us check our maths: The following tag list
    # should be exclusive of the all-github tags list.
    #
    # Note that using --tags all-tasks won't actually run any task, but
    # we specify it here because convention.
    - all-tasks
    #
    - app-chrome
    - app-cinelerra-gg
    - app-darktable
    - app-digikam
    - app-openjump
    - app-opera
    - app-pencil-project-evolus
    - app-spotify
    - app-virtualbox-apt
    - app-virtualbox-deb
    - cli-ripgrep
    - dmn-dropbox
    - email-gmail-postfix
    - font-hack-classic
    - font-mania
    - golang-go-install-packages
    - hardware-android-studio
    - hardware-arduino
    - node-npm-packages
    - meld-configure
    - python-sources
    - virt-vagrant

