---

# USAGE: Task installs GIMP wavelet-decompose plugin.

# ***

# DUNNO/2023-04-23: GIMP includes a plug-in with the same name:
#
# - GIMP > Help > Plug-in Browser > Wavelet-decompose
#
#     Date: 19january 2017
#     Copyright: Miroslav Talasek <miroslav.talasek@seznam.cz>
#
# - Whereas this plugin
#
#   - CXREF: https://github.com/gimp-plugins-justice/wavelet-decompose
#
#   Is 9 years stale, replaces the built-in plug-in, and reports:
#
#     Copyright: Copyright 2008 Marco Rossini
#
# So making this plug-in opt-in.

- name: Clone wavelet-decompose repo
  ansible.builtin.git:
    repo: "git@github.com:gimp-plugins-justice/wavelet-decompose.git"
    dest: "{{ zoidy_homefries_downloads_dir }}/wavelet-decompose"

# ***

- name: Run command "apt-get update" (app-gimp-plugin-wavelet-decompose)
  become: true
  ansible.builtin.apt:
    update_cache: yes
    # Skip the cache time so that the new repo gets picked up.
    #   cache_valid_time: 3600

- name: Install GIMP development headers, etc.
  become: true
  ansible.builtin.apt: name=libgimp2.0-dev

# ***

- name: Build wavelet-decompose plugin
  ansible.builtin.make:
    chdir: "{{ zoidy_homefries_downloads_dir }}/wavelet-decompose"

# ***

# make-install calls something
#
#   $ gimptool-2.0 --install-bin <>
#   cp '<>' '/home/user/.config/GIMP/2.10/plug-ins/<>/'
#
# And installs to, e.g.,
#
#   ~/.config/GIMP/2.10/plug-ins/wavelet-decompose/

- name: Install wavelet-decompose for all users
  become: true
  ansible.builtin.make:
    target: install
    chdir: "{{ zoidy_homefries_downloads_dir }}/wavelet-decompose"
  when: False

- name: Install wavelet-decompose for your user
  ansible.builtin.make:
    chdir: "{{ zoidy_homefries_downloads_dir }}/wavelet-decompose"
    target: userinstall
  when: True

