---

# USAGE: Task installs GIMP export-layers plugin.

# ***

# SAVVY/2023-04-23: If you installed GIMP from aptitude (or at least this is
# how apt's GIMP 2.8 worked), the plugins dir is, e.g., ~/.gimp-2.8/plug-ins.
#
#   - ansible.builtin.set_fact:
#       zoidy_gimp_minor_version: "2.10"
#
#   - ansible.builtin.set_fact:
#       zoidy_gimp_plug_ins_dir: "{{ ansible_env.HOME }}/.gimp-{{ zoidy_gimp_minor_version }}/plug-ins"
#
# But Flatpak GIMP (which we now expect) installs elsewhere.
#
# - SAVVY: Determine the plug-ins directory:
#
#     GIMP > Edit > Preferences > Folders > Plug-ins
#
#   - E.g., ~/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins
#
# - SAVVY: Determine where gimptool-2.0 installs:
#
#     $ gimptool-2.0 --install-bin -n
#     cp '-n' '/home/user/.config/GIMP/2.10/plug-ins/-n/'
#
# - SAVVY: There's also a directory under the Flatpak installation
#   directory, but didn't work when I tested:
#
#     ~/.local/share/flatpak/app/org.gimp.GIMP/current/active/files/lib/gimp/2.0/plug-ins
#
# The ~/.var and ~/.config paths both work. We'll use ~/.config because
# that's what gimptool-2.0 uses.

- ansible.builtin.set_fact:
    # E.g., ~/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins
    #  zoidy_gimp_plug_ins_dir: "{{ ansible_env.HOME }}/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins"
    # E.g., ~/.config/GIMP/2.10/plug-ins
    zoidy_gimp_plug_ins_dir: "{{ ansible_env.HOME }}/.config/GIMP/2.10/plug-ins"

# ***

# CXREF: https://github.com/khalim19/gimp-plugin-export-layers
- name: Clone gimp-plugin-export-layers repo
  ansible.builtin.git:
    repo: "git@github.com:khalim19/gimp-plugin-export-layers.git"
    dest: "{{ zoidy_homefries_downloads_dir }}/gimp-plugin-export-layers"

# ***

# [lb]: 2019-01-06: If you download and extract the installer from GitHub,
#   e.g., from
#
#     https://github.com/khalim19/gimp-plugin-export-layers/releases/download
#       /3.2.1/export_layers-3.2.1-linux.zip
#
#   You'll see a single, executable file:
#
#     export_layers-3.2.1-linux.run
#
#   which copies basically the export_layers directory (but without tests/)
#   and also the export_layers.py executable. And that's it. So keep it simple
#   and just do the same here, and then we can run bleeding-edge code, and also
#   not worry if anything is lurking in the single-file encoded archive (not
#   that I audited the raw project code, but whatever, feelings are feelings).

# The ~/.var/app/org.gimp.GIMP/ directory not created until first run.
- name: Ensure the GIMP & Its Plug-Ins Directories exist
  ansible.builtin.file: path="{{ zoidy_gimp_plug_ins_dir }}" state=directory

- name: Synchronize GIMP export_layers plug-in directory
  ansible.builtin.synchronize:
    src: "{{ zoidy_homefries_downloads_dir }}/gimp-plugin-export-layers/export_layers/"
    dest: "{{ zoidy_gimp_plug_ins_dir }}/export_layers/"
    delete: yes
  # Copy from remote to remote.
  delegate_to: "{{ inventory_hostname }}"

- name: Copy export_layers.py to GIMP plug-ins
  ansible.builtin.copy:
    src: "{{ zoidy_homefries_downloads_dir }}/gimp-plugin-export-layers/export_layers.py"
    dest: "{{ zoidy_gimp_plug_ins_dir }}/"
    remote_src: yes
    # Even if source file is executable, copied file defaults to 0664.
    mode: 0775

