---

# USAGE: Install Opera browser apt package.

# ***

# REFER: Install apt package from Opera sources, as documented by:
#   https://www.linuxcapable.com/install-opera-browser-on-ubuntu-linux/

# REFER: For .deb package, see:
#   https://www.opera.com/download/
#   https://www.opera.com/computer/thanks?partner=www&par=id%3D61294%26location%3D424&gaprod=opera

# SAVVY: Creates /usr/share/keyrings/opera.gpg
# - 2024-02-08: You might also see two other keys, but might also be
#   artifacts from a manual .deb install:
#     /etc/apt/trusted.gpg.d/opera.archive.key.2019.gpg
#     /etc/apt/trusted.gpg.d/opera.archive.key.2021.gpg
- name: Import Opera Public Key
  become: true
  ansible.builtin.shell: >
    curl -fsSL https://deb.opera.com/archive.key |
      gpg --dearmor |
      sudo tee /usr/share/keyrings/opera.gpg \
      > /dev/null

- name: Import Opera Public Key
  become: true
  ansible.builtin.shell: >
    echo deb [arch=amd64 signed-by=/usr/share/keyrings/opera.gpg] \
      https://deb.opera.com/opera-stable/ stable non-free |
      sudo tee /etc/apt/sources.list.d/opera-stable.list

- name: Run command "apt-get update"
  become: true
  ansible.builtin.apt: update_cache=yes

- name: Install opera-stable
  become: true
  ansible.builtin.apt: name=opera-stable

