---

# USAGE: Task installs Spotify from third-party apt repo.

# ***

# CXREF/2023-04-22:
#
#   https://www.spotify.com/us/download/linux/

# ***

# Cannot simply get_url because --dearmor necessary.
#
#  ansible.builtin.get_url:
#    url: https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg
#    dest: /etc/apt/trusted.gpg.d/spotify.gpg

# SAVVY/2023-04-23: ansible.builtin.apt_key is deprecated.

- name: Add Spotify keyserver and key signature to receive
  become: true
  ansible.builtin.shell: >
    curl -sS https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg \
      | sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/spotify.gpg

# E.g.,
#   echo "deb http://repository.spotify.com stable non-free" \
#     | sudo tee -a /etc/apt/sources.list &> /dev/null
- name: Add Spotify proprietary repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present

- name: Run command "apt-get update" (app-spotify)
  become: true
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: 'Install Spotify desktop client application'
  become: true
  ansible.builtin.apt:
    name: spotify-client
    state: present

