---

# USAGE: Task installs digiKam AppImage.

# ***

# CXREF: https://www.digikam.org/download/
#
# - 2024-02-08: 8.2.0: Known hashes:
#   - REFER:  https://download.kde.org/stable/digikam/8.2.0/digiKam-8.2.0-x86-64.appimage.mirrorlist
#   - File:   /stable/digikam/8.2.0/digiKam-8.2.0-x86-64.appimage
#   - MD5     8f89c25c64cd26c877b33e6a733f23d5
#   - SHA1    08e1373d64438625595aa94c8465affc8e56a292
#   - SHA256  2176dceedf62697e342f4fa2e06d1afa60d662cf2e57bc8a9ad1d7f5eb60b2a8
#
# - 2023-04-23: 8.0.0: Known hashes:
#   - REFER:  https://download.kde.org/stable/digikam/8.0.0/digiKam-8.0.0-x86-64.appimage.mirrorlist
#   - File:   /stable/digikam/8.0.0/digiKam-8.0.0-x86-64.appimage
#   - MD5     e62cf3f2bdc5ecb1f8a52f9cdaf6bc15
#   - SHA1    b12742bad5ff934cdb17440e8621cd09249f9c73
#   - SHA256  d73bc5dcc97d6f7e378b58af44387f213d556510ad496a80898fd69131b87eea
#
# Version history I've used: 5.90, 6.4.0, 7.8.0, 8.0.0

- ansible.builtin.set_fact:
    zoidy_digikam_version: "8.2.0"
    zoidy_digikam_sha256: "2176dceedf62697e342f4fa2e06d1afa60d662cf2e57bc8a9ad1d7f5eb60b2a8"

- ansible.builtin.set_fact:
    zoidy_digikam_uri: "https://mnvoip.mm.fcix.net/kdeftp/stable/digikam/{{ zoidy_digikam_version }}"
    zoidy_digikam_basename: "digiKam-{{ zoidy_digikam_version }}-x86-64"

- ansible.builtin.set_fact:
    zoidy_digikam_appimage: "{{ zoidy_digikam_basename }}.appimage"

# E.g., https://mnvoip.mm.fcix.net/kdeftp/stable/digikam/8.0.0/digiKam-8.0.0-x86-64.appimage
- name: "Download digiKam AppImage"
  ansible.builtin.get_url:
    url: "{{ zoidy_digikam_uri }}/{{ zoidy_digikam_appimage }}"
    dest: "{{ zoidy_homefries_downloads_dir }}/{{ zoidy_digikam_appimage }}"
    checksum: "sha256:{{ zoidy_digikam_sha256 }}"
  # YOU: Uncomment to re-test this task easily, once appimage downloaded.
  #  when: False

# ***

- ansible.builtin.set_fact:
    zoidy_digikam_signature: "{{ zoidy_digikam_appimage }}.sig"
    # Get public key: gpg {{ zoidy_digikam_signature }}

- name: "Download digiKam Signature"
  ansible.builtin.get_url:
    url: "{{ zoidy_digikam_uri }}/{{ zoidy_digikam_signature }}"
    dest: "{{ zoidy_homefries_downloads_dir }}/{{ zoidy_digikam_signature }}"
  when: "{{ not zoidy_digikam_sha256 }}"

- name: "Import digiKam Signing Key"
  ansible.builtin.command: "gpg --recv-key D1CF2444A7858C5F2FB095B74A77747BC2386E50"
  when: "{{ not zoidy_digikam_sha256 }}"

- name: "Verify digiKam Download"
  ansible.builtin.command: "gpg {{ zoidy_digikam_signature }}"
  args:
    chdir: "{{ zoidy_homefries_downloads_dir }}"
  when: "{{ not zoidy_digikam_sha256 }}"

# ***

- name: "Make the AppImage executable"
  ansible.builtin.file:
    path: "{{ zoidy_homefries_downloads_dir }}/{{ zoidy_digikam_appimage }}"
    mode: 0755

- name: "Symlink digiKam AppImage from user bin/"
  ansible.builtin.file:
    src: "{{ zoidy_homefries_downloads_dir }}/{{ zoidy_digikam_appimage }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/digiKam"
    state: link

