---

# USAGE: Task downloads and installs OpenJUMP app from zip archives.

# ***

# CXREF:
#
#   https://sourceforge.net/projects/jump-pilot/files/OpenJUMP/
#
#   https://sourceforge.net/projects/jump-pilot/files/OpenJUMP/2.2.1/

- ansible.builtin.set_fact:
    # 2024-02-08 (2023-05-07):
    OPENJUMP_VER: '2.2.1'
    OPENJUMP_BLD: 'r5222[94156e5]'
    OPENJUMP_BLD_ENC: 'r5222%5B94156e5%5D'
    # 2023-04-25 (2022-12-04):
    #  OPENJUMP_VER: '2.2.0'
    #  OPENJUMP_BLD: 'r5193[9e7ba88]'
    #  OPENJUMP_BLD_ENC: 'r5193%5B9e7ba88%5D'
    # 2019-01-03:
    #  OPENJUMP_VER: '1.14'
    #  OPENJUMP_BLD: 'r6065'

- ansible.builtin.set_fact:
    OPENJUMP_BASE_URI: 'https://downloads.sourceforge.net/project/jump-pilot/OpenJUMP/{{ OPENJUMP_VER }}'
    OPENJUMP_BASE_ZIP: "OpenJUMP-Portable-{{ OPENJUMP_VER }}-{{ OPENJUMP_BLD_ENC }}"

# E.g.,
# - OpenJUMP-Portable-2.2.0-r5193[9e7ba88]-PLUS.zip:
#   https://sourceforge.net/projects/jump-pilot/files/OpenJUMP/2.2.0/OpenJUMP-Portable-2.2.0-r5193%5B9e7ba88%5D-PLUS.zip/download
# - OpenJUMP-Portable-2.2.0-r5193[9e7ba88]-CORE.zip:
#   https://sourceforge.net/projects/jump-pilot/files/OpenJUMP/2.2.0/OpenJUMP-Portable-2.2.0-r5193%5B9e7ba88%5D-CORE.zip/download
- ansible.builtin.set_fact:
    OPENJUMP_CORE_ZIP: "{{ OPENJUMP_BASE_ZIP }}-CORE.zip"
    OPENJUMP_PLUS_ZIP: "{{ OPENJUMP_BASE_ZIP }}-PLUS.zip"

- ansible.builtin.set_fact:
    OPENJUMP_CORE_URI: "{{ OPENJUMP_BASE_URI }}/{{ OPENJUMP_CORE_ZIP }}"
    OPENJUMP_PLUS_URI: "{{ OPENJUMP_BASE_URI }}/{{ OPENJUMP_PLUS_ZIP }}"

- ansible.builtin.set_fact:
    OPENJUMP_DIR: "{{ zoidy_homefries_downloads_dir }}/OpenJUMP"

- ansible.builtin.set_fact:
    OPENJUMP_PLUS_DIR: "OpenJUMP-{{ OPENJUMP_VER }}-{{ OPENJUMP_BLD }}-PLUS"

# ***

- name: Fetch OpenJUMP CORE
  ansible.builtin.get_url:
    url: "{{ OPENJUMP_CORE_URI }}"
    dest: "{{ zoidy_homefries_downloads_dir }}/"

- name: Fetch OpenJUMP PLUS
  ansible.builtin.get_url:
    url: "{{ OPENJUMP_PLUS_URI }}"
    dest: "{{ zoidy_homefries_downloads_dir }}/"

# ***

- name: Ensure OpenJUMP unpack directory exists
  ansible.builtin.file: path="{{ OPENJUMP_DIR }}" state=directory

- name: Unarchive the OpenJUMP release archive
  ansible.builtin.unarchive:
    src: "{{ zoidy_homefries_downloads_dir }}/{{ OPENJUMP_PLUS_ZIP }}"
    dest: "{{ OPENJUMP_DIR }}/"
    remote_src: yes

# ***

- name: Symlink oj_linux.sh from user bin
  ansible.builtin.file:
    src: "{{ OPENJUMP_DIR }}/{{ OPENJUMP_PLUS_DIR }}/bin/oj_linux.sh"
    dest: "{{ ansible_env.HOME }}/.local/bin/oj_linux.sh"
    state: link

- name: Symlink OpenJUMP from user bin
  ansible.builtin.file:
    src: "{{ OPENJUMP_DIR }}/{{ OPENJUMP_PLUS_DIR }}/bin/oj_linux.sh"
    dest: "{{ ansible_env.HOME }}/.local/bin/OpenJUMP"
    state: link

