---

# CXREF: https://www.digikam.org/download/
#
#   https://download.kde.org/stable/digikam/8.0.0/digiKam-8.0.0-x86-64.appimage.mirrorlist
#
# - 8.0.0: Known hashes:
#   - File:   /stable/digikam/8.0.0/digiKam-8.0.0-x86-64.appimage
#   - MD5     e62cf3f2bdc5ecb1f8a52f9cdaf6bc15
#   - SHA1    b12742bad5ff934cdb17440e8621cd09249f9c73
#   - SHA256  d73bc5dcc97d6f7e378b58af44387f213d556510ad496a80898fd69131b87eea
#
# Version history I've used: 5.90, 6.4.0, 7.8.0, 8.0.0

- set_fact:
    zoidy_digikam_version: "8.0.0"
    zoidy_digikam_sha256: "d73bc5dcc97d6f7e378b58af44387f213d556510ad496a80898fd69131b87eea"

- set_fact:
    zoidy_digikam_uri: "https://mnvoip.mm.fcix.net/kdeftp/stable/digikam/{{ zoidy_digikam_version }}"
    zoidy_digikam_basename: "digiKam-{{ zoidy_digikam_version }}-x86-64"

- set_fact:
    zoidy_digikam_appimage: "{{ zoidy_digikam_basename }}.appimage"

# E.g., https://mnvoip.mm.fcix.net/kdeftp/stable/digikam/8.0.0/digiKam-8.0.0-x86-64.appimage
- name: "Download digiKam AppImage"
  get_url:
    url: "{{ zoidy_digikam_uri }}/{{ zoidy_digikam_appimage }}"
    dest: "{{ zoidy_homefries_downloads_dir }}/{{ zoidy_digikam_appimage }}"
    checksum: "sha256:{{ zoidy_digikam_sha256 }}"
  # YOU: Uncomment to re-test this task easily, once appimage downloaded.
  #  when: False

# ***

- set_fact:
    zoidy_digikam_signature: "{{ zoidy_digikam_appimage }}.sig"
    # Get public key: gpg {{ zoidy_digikam_signature }}

- name: "Download digiKam Signature"
  get_url:
    url: "{{ zoidy_digikam_uri }}/{{ zoidy_digikam_signature }}"
    dest: "{{ zoidy_homefries_downloads_dir }}/{{ zoidy_digikam_signature }}"
  when: "{{ not zoidy_digikam_sha256 }}"

- name: "Import digiKam Signing Key"
  command: "gpg --recv-key D1CF2444A7858C5F2FB095B74A77747BC2386E50"
  when: "{{ not zoidy_digikam_sha256 }}"

- name: "Verify digiKam Download"
  command: "gpg {{ zoidy_digikam_signature }}"
  args:
    chdir: "{{ zoidy_homefries_downloads_dir }}"
  when: "{{ not zoidy_digikam_sha256 }}"

# ***

- name: "Make the AppImage executable"
  file:
    path: "{{ zoidy_homefries_downloads_dir }}/{{ zoidy_digikam_appimage }}"
    mode: 0755

- name: "Symlink digiKam AppImage from user bin/"
  file:
    src: "{{ zoidy_homefries_downloads_dir }}/{{ zoidy_digikam_appimage }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/digiKam"
    state: link

