---

# Firefox scrollbar jumping to where I click, instead of paging.
# You can shift-click to do opposite behavior
#
# https://support.mozilla.org/en-US/questions/1125603
- name: Ensure "gtk-primary-button-warps-slider=false" is in section "[Settings]" in gtk-3.0 .config INI
  ini_file:
    path: "{{ ansible_env.HOME }}/.config/gtk-3.0/settings.ini"
    section: Settings
    option: gtk-primary-button-warps-slider
    value: "false"

