---

# USAGE: Task installs VirtualBox from third-party apt repo.

# ***

- name: Add Oracle VM VirtualBox repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ zoidy_distrib_codename }} contrib"
    state: present
    # To disable:
    #  state: absent

- name: Run command "apt-get update" (app-virtualbox)
  become: true
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install VirtualBox (app-virtualbox)
  become: true
  ansible.builtin.apt:
    name: virtualbox-6.1
    state: present

# FIXME/2020-04-26 15:01: Missing the Extension Pack, according to Vagrant.
#
# - Download:
#
#   https://download.virtualbox.org/virtualbox/6.1.6/Oracle_VM_VirtualBox_Extension_Pack-6.1.6.vbox-extpack
#
# - Install:
#
#   VBoxManage extpack install Oracle_VM_VirtualBox_Extension_Pack-6.1.6.vbox-extpack

