---

# USAGE: (Deprecated) Task installs VirtualBox from third-party deb download.

# ***

# BWARE/2023-04-27: This task preserved for posterity, but I haven't installed
# VirtualBox from the deb download since VBox v5 (circa 2019-03-14).
#
# - I've use the apt install for the past 2 VBox versions, v6.1, and v7.0.
#
# - So this task may or may not work, with or without tweaks; who knows.

# ***

# BWARE/2023-04-27: You might find signing issues when installing the deb package.
# - From a note I made 4 years ago:
#
#   - 2019-03-14: Because Secure Boot (I think that's it), need to sign
#     VirtualBox drivers.
#   
#     So this task will run, but you won't be able to boot any virtual machines.
#
# CXREF/2023-04-27: If you do revive this task, and if you hit signing problems,
# see the old signing task I developed:
#
#   https://github.com/landonb/zoidy_virtualbox/blob/release/tasks/app-virtualbox-5-sign.yml
#
#     ~/.kit/ansible/roles/zoidy_virtualbox/tasks/app-virtualbox-5-sign.yml  

# ***

# ansible_facts.kernel » Same as `uname -r`
- ansible.builtin.set_fact:
    zoidy_headers_kernel: linux-headers-{{ ansible_kernel }}

- name: 'Install linux headers required by VirtualBox'
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:
    - linux-headers-generic
    - "{{ zoidy_headers_kernel }}"

# ***

# USYNC/2023-04-27: The two VBox tasks that download files share the next
# 2 sections (5 tasks). Not a lot of code, but keep them aligned, e.g.,
#
#     cd ~/.kit/ansible/roles/zoidy_apps_et_al/tasks
#     meld app-virtualbox-extpack.yml app-virtualbox-deb.yml &

- name: Fetch latest VirtualBox version file
  ansible.builtin.get_url:
    url: "http://download.virtualbox.org/virtualbox/LATEST.TXT"
    dest: "{{ zoidy_virtualbox_downloads_dir }}/virtualbox-LATEST.TXT"

- name: Read VirtualBox latest version file
  ansible.builtin.command: cat "{{ zoidy_virtualbox_downloads_dir }}/virtualbox-LATEST.TXT"
  register: virtualbox_latest_version_raw

- ansible.builtin.set_fact:
    virtualbox_latest_version: "{{ virtualbox_latest_version_raw.stdout }}"

# ***

- ansible.builtin.set_fact:
    zoidy_vbox_version_index: "virtualbox-version-{{ virtualbox_latest_version }}-index.htm"

- ansible.builtin.set_fact:
    zoidy_vbox_version_path: "{{ zoidy_virtualbox_downloads_dir }}/{{ zoidy_vbox_version_index }}"

# E.g., http://download.virtualbox.org/virtualbox/7.0.8/
- name: 'Fetch latest VirtualBox builds directory list'
  ansible.builtin.get_url:
    url: "http://download.virtualbox.org/virtualbox/{{ virtualbox_latest_version }}/"
    dest: "{{ zoidy_vbox_version_path }}"

- name: Read VirtualBox latest build URI
  # Yaml lesson: `shell: |` multiline preserves newlines, so `\` continuations required.
  #   `shell: >` multiline gobbles newlines, so Bash line continuations unnecessary.
  ansible.builtin.shell: >
    /bin/grep "{{ zoidy_distrib_codename }}_amd64" {{ zoidy_vbox_version_path }}
    | sed -E s/\<[^\>]*\>//g
    | sed -E s/^[\ ]\+\(.*\.deb\).*$/\\1/
  register: virtualbox_deb_pkg

- ansible.builtin.fail: msg="Undiscerned download URL!"
  when: not virtualbox_deb_pkg.stdout

# ***

# 2023-04-26: virtualbox-7.0_7.0.8-156879~Ubuntu~jammy_amd64.deb:
#   checksum: a5e721c333aeea6301303cefbd1cf7a8520655634f54dc8c32bb3beff73f5ebf

- name: 'Download latest VirtualBox'
  ansible.builtin.get_url:
    # E.g.,
    #   https://download.virtualbox.org/virtualbox/6.0.0/virtualbox-6.0_6.0.0-127566~Ubuntu~bionic_amd64.deb
    #   https://download.virtualbox.org/virtualbox/7.0.8/virtualbox-7.0_7.0.8-156879~Ubuntu~jammy_amd64.deb
    url: "https://download.virtualbox.org/virtualbox/{{ virtualbox_latest_version }}/{{ virtualbox_deb_pkg.stdout }}"
    dest: "{{ zoidy_virtualbox_downloads_dir }}/{{ virtualbox_deb_pkg.stdout }}"
    checksum: "sha256:http://download.virtualbox.org/virtualbox/{{ virtualbox_latest_version }}/SHA256SUMS"

# E.g., sudo dpkg -i <pkg>
- name: Install VirtualBox package
  become: yes
  ansible.builtin.apt:
    deb: "{{ zoidy_virtualbox_downloads_dir }}/{{ virtualbox_deb_pkg.stdout }}"

# ***

- name: Remove old VirtualBox indices
  # E.g., ./oracle_virtualbox_download_index_5.1.6.html
  # Yaml lesson: Even though `>` used, `\` continuation needed
  # when continued lines begin with whitespace.
  ansible.builtin.shell: >
    find . -maxdepth 1 \
      -name "virtualbox-version-[0-9]*\\.[0-9]*\\.[0-9]*-index\\.htm" \
      -exec echo {} + \
    | sed s/\\.\\/{{ zoidy_vbox_version_index }}// \
    | xargs /bin/rm &> /dev/null
    # | xargs echo
  args:
    chdir: "{{ zoidy_virtualbox_downloads_dir }}"
  # register: zoidy_rm_vbox_indices

# - ansible.builtin.debug: msg="zoidy_rm_vbox_indices » {{ zoidy_rm_vbox_indices.stdout }}"

- name: Remove old VirtualBox packages
  # E.g., ./virtualbox-5.1_5.1.6-110634~Ubuntu~trusty_amd64.deb
  ansible.builtin.shell: >
    find . -maxdepth 1 \
      -name "virtualbox-[0-9]*\\.[0-9]*_[0-9]*\\.[0-9]*\\.[0-9]*-[0-9]*~Ubuntu~[a-zA-Z0-9]*_[a-zA-Z0-9]*\\.deb" \
      -exec echo {} + \
      | sed s/\\.\\/virtualbox-[0-9]*\\.[0-9]*_{{ virtualbox_latest_version }}-[0-9]*~Ubuntu~[a-zA-Z0-9]*_[a-zA-Z0-9]*\\.deb// \
      | xargs /bin/rm &> /dev/null
      # | xargs echo
  args:
    chdir: "{{ zoidy_virtualbox_downloads_dir }}"
  # register: zoidy_rm_vbox_packages

# - ansible.builtin.debug: msg="zoidy_rm_vbox_packages » {{ zoidy_rm_vbox_packages.stdout }}"

# ***

- name: 'Add user to VirtualBox groups'
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.LOGNAME }}"
    # INERT/2019-03-14: Maybe add back vboxsf (I think that's the shared file system driver).
    #  groups: vboxsf, vboxusers
    groups: vboxusers
    append: yes

- ansible.builtin.debug: msg="CHORE: ALERT: You must logoff and log back on to realize the 'vboxusers' group association"

