---

# - set_fact:
#     zoidy_digikam_version: '5.9.0'
#     # https://download.kde.org/stable/digikam/digikam-5.9.0-01-x86-64.appimage.sha256
#     #   da14b81304ca19eb148882f2b3d5bed5146de845f87f1baa2338b26e770d9d76  digikam-5.9.0-01-x86-64.appimage
#     zoidy_digikam_sha256: 'da14b81304ca19eb148882f2b3d5bed5146de845f87f1baa2338b26e770d9d76'

- set_fact:
    zoidy_digikam_version: '6.4.0'

- set_fact:
    zoidy_digikam_uri: "https://download.kde.org/stable/digikam/{{ zoidy_digikam_version }}"
    zoidy_digikam_basename: "digikam-{{ zoidy_digikam_version }}-x86-64"

- set_fact:
    zoidy_digikam_appimage: "{{ zoidy_digikam_basename }}.appimage"

- name: 'Download Digikam AppImage'
  get_url:
    url: "{{ zoidy_digikam_uri }}/{{ zoidy_digikam_appimage }}"
    dest: "{{ zoidy_homefries_downloads_dir }}/{{ zoidy_digikam_appimage }}"
  # YOU: Uncomment to re-test this task easily, once appimage downloaded.
  when: False

# ***

- set_fact:
    zoidy_digikam_signature: "{{ zoidy_digikam_appimage }}.sig"
    # Get public key: gpg {{ zoidy_digikam_signature }}

- name: 'Download Digikam Signature'
  get_url:
    url: "{{ zoidy_digikam_uri }}/{{ zoidy_digikam_signature }}"
    dest: "{{ zoidy_homefries_downloads_dir }}/{{ zoidy_digikam_signature }}"

- name: Import Digikam Signing Key
  command: "gpg --recv-key D1CF2444A7858C5F2FB095B74A77747BC2386E50"

- name: Verify Digikam Download
  command: "gpg {{ zoidy_digikam_signature }}"
  args:
    chdir: "{{ zoidy_homefries_downloads_dir }}"

# ***

- name: Make the AppImage executable
  file:
    path: "{{ zoidy_homefries_downloads_dir }}/{{ zoidy_digikam_appimage }}"
    mode: 0755

- name: Symlink Digikam AppImage from user bin/
  file:
    src: "{{ zoidy_homefries_downloads_dir }}/{{ zoidy_digikam_appimage }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/digikam"
    state: link

