---

# USAGE: Task builds and installs tmux from GitHub sources.

# ***

# *** Local variables (Facts).

# YOU: If you've checked out the repo elsewhere, set:
#
#   zoidy_homefries_tmux_repo_path
#
# Otherwise we'll fetch it for you.

# USYNC/2020-02-06: Keep this updated.
# - MAYBE/2023-04-22: Suss version automatically.

# SAVVY/2024-02-07 15:40: LM 21.3 installs tmux 3.2a.

- ansible.builtin.set_fact:
    # CXREF: https://github.com/tmux/tmux/releases
    # 2024-02-07: Latest release still 2022-06-09.
    TMUX_BRANCH: "3.3a"

# ***

- ansible.builtin.set_fact:
    TMUX_DIR: "{{ zoidy_homefries_tmux_repo_path }}"

- ansible.builtin.set_fact:
    TMUX_DIR: "{{ zoidy_homefries_downloads_dir }}/tmux"
  when: TMUX_DIR == ""

# ***

- name: 'Install libevent-dev'
  become: true
  ansible.builtin.apt: name=libevent-dev

# ***

- name: "tmux: git clone"
  ansible.builtin.git:
    repo: "git@github.com:tmux/tmux.git"
    dest: "{{ TMUX_DIR }}"
    remote: "{{ zoidy_homefries_tmux_repo_remote }}"
    version: "{{ TMUX_BRANCH }}"
    # BADEV/2023-04-22: Huh, repo maintainer tagged 3.1-rc as '3.1'
    # and then replaced '3.0' and '3.1' tags on a commit after that.
    # - Use --force to replace tags. Or anything else, don't care.
    force: "true"
  register: gitclone

- name: "tmux: make clean"
  ansible.builtin.make:
    chdir: "{{ TMUX_DIR }}"
    target: clean

- name: "tmux: sh autogen.sh"
  ansible.builtin.shell: sh autogen.sh
  args:
    chdir: "{{ TMUX_DIR }}"
#  when: gitclone.changed or not kcov_symlink.stat.exists

- name: "tmux: configure"
  ansible.builtin.shell: >
    CPPFLAGS="-I{{ ansible_env.HOME }}/.local/include" \
      LDFLAGS="-L{{ ansible_env.HOME }}/.local/lib" \
      ./configure --prefix={{ ansible_env.HOME }}/.local
  args:
    chdir: "{{ TMUX_DIR }}"

- name: "tmux: make"
  ansible.builtin.make:
    chdir: "{{ TMUX_DIR }}"

- name: "tmux: make install"
  ansible.builtin.make:
    chdir: "{{ TMUX_DIR }}"
    target: install

# ***

- name: "tmux: symlink man"
  ansible.builtin.file:
    src: "{{ TMUX_DIR }}/tmux.1"
    dest: "{{ ansible_env.HOME }}/.local/man/man1/tmux.1"
    state: link

- name: "tmux: rebuild man"
  ansible.builtin.shell: mandb

