---

# https://docs.gimp.org/download.html

- set_fact:
    # LATST/2023-04-11: "2.10.34 User Manual Source (Release Date: 2023-03-05)"
    zoidy_gimp_manual_version: "2.10.34"
    zoidy_gimp_manual_sha256: "cae0adea6ffe47776f42dfc3a38f35d28e31893004e01812117af6f7fc897dc8"

- set_fact:
    # E.g., https://download.gimp.org/mirror/pub/gimp/help/gimp-help-2.10.34.tar.bz2
    zoidy_gimp_manual_uri_base_dir: "https://download.gimp.org/mirror/pub/gimp/help"
    zoidy_gimp_manual_archive_name: "gimp-help-{{ zoidy_gimp_manual_version }}.tar.bz2"

# Bah, why no PDF of the help for 2.8?
# http://docs.gimp.org/2.8/en/
- name: Download GIMP {{ zoidy_gimp_manual_version }} Manual Archive (bz2)
  get_url:
    url: "{{ zoidy_gimp_manual_uri_base_dir }}/{{ zoidy_gimp_manual_archive_name }}"
    # E.g., ~/.local/docs
    dest: "{{ zoidy_homefries_user_docs_dir }}/{{ zoidy_gimp_manual_archive_name }}"
    checksum: "sha256:{{ zoidy_gimp_manual_sha256 }}"

- name: Unpack GIMP {{ zoidy_gimp_manual_version }} Manual Document (pdf)
  command: "tar --bzip2 -xf {{ zoidy_gimp_manual_archive_name }}"
  args:
    chdir: "{{ zoidy_homefries_user_docs_dir }}"

# 2023-04-11: The latest manual archive is 158 MB, so remove archive source.
- name: Delete GIMP {{ zoidy_gimp_manual_version }} Manual Archive (bz2)
  file:
    path: "{{ zoidy_homefries_user_docs_dir }}/{{ zoidy_gimp_manual_archive_name }}"
    state: absent

