---

# https://sourceforge.net/projects/jump-pilot/files/OpenJUMP/1.14/

- set_fact:
    OPENJUMP_VER: '1.14'
    OPENJUMP_BLD: 'r6065'

- set_fact:
    OPENJUMP_BASE_URI: 'https://downloads.sourceforge.net/project/jump-pilot/OpenJUMP/{{ OPENJUMP_VER }}'
    OPENJUMP_BASE_ZIP: "OpenJUMP-Portable-{{ OPENJUMP_VER }}-{{ OPENJUMP_BLD }}"
    OPENJUMP_BASE_UZP: "OpenJUMP-{{ OPENJUMP_VER }}-{{ OPENJUMP_BLD }}"

- set_fact:
    OPENJUMP_CORE_ZIP: "{{ OPENJUMP_BASE_ZIP }}-CORE.zip"
    OPENJUMP_PLUS_ZIP: "{{ OPENJUMP_BASE_ZIP }}-PLUS.zip"

- set_fact:
    OPENJUMP_CORE_URI: "{{ OPENJUMP_BASE_URI }}/{{ OPENJUMP_CORE_ZIP }}"
    OPENJUMP_PLUS_URI: "{{ OPENJUMP_BASE_URI }}/{{ OPENJUMP_PLUS_ZIP }}"

- set_fact:
    OPENJUMP_DIR: "{{ zoidy_homefries_downloads_dir }}/OpenJUMP"

- set_fact:
    OPENJUMP_CORE_DIR: "{{ OPENJUMP_BASE_UZP }}-CORE"
    OPENJUMP_PLUS_DIR: "{{ OPENJUMP_BASE_UZP }}-PLUS"

# ***

- name: Fetch OpenJUMP CORE
  get_url:
    url: "{{ OPENJUMP_CORE_URI }}"
    dest: "{{ zoidy_homefries_downloads_dir }}/"

- name: Fetch OpenJUMP PLUS
  get_url:
    url: "{{ OPENJUMP_PLUS_URI }}"
    dest: "{{ zoidy_homefries_downloads_dir }}/"

# ***

- name: Ensure OpenJUMP unpack directory exists
  file: path="{{ OPENJUMP_DIR }}" state=directory

- name: Unarchive the OpenJUMP release archive
  unarchive:
    src: "{{ zoidy_homefries_downloads_dir }}/{{ OPENJUMP_PLUS_ZIP }}"
    dest: "{{ OPENJUMP_DIR }}/"
    remote_src: yes

# ***

- name: Symlink oj_linux.sh from user bin
  file:
    src: "{{ zoidy_homefries_downloads_dir }}/OpenJUMP/{{ OPENJUMP_PLUS_DIR }}/bin/oj_linux.sh"
    dest: "{{ ansible_env.HOME }}/.local/bin/oj_linux.sh"
    state: link

- name: Symlink OpenJUMP from user bin
  file:
    src: "{{ zoidy_homefries_downloads_dir }}/OpenJUMP/{{ OPENJUMP_PLUS_DIR }}/bin/oj_linux.sh"
    dest: "{{ ansible_env.HOME }}/.local/bin/OpenJUMP"
    state: link

