---

# CXREF:
#
#   https://www.google.com/chrome/thank-you.html?brand=QMKX&statcb=0&installdataindex=empty&defaultbrowser=0#

- name: Add Google Chrome proprietary repository
  become: true
  apt_repository:
    # $ apt show google-chrome-stable
    # ...
    # APT-Sources: https://dl.google.com/linux/chrome/deb stable/main amd64 Packages
    #
    # CXREF: /etc/apt/sources.list.d/google-chrome.list
    repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb stable main
    state: present

- name: Run command "apt-get update"
  become: true
  apt: update_cache=yes

- name: Install google-chrome-stable
  become: true
  apt: name=google-chrome-stable

# ***

# REFER/2023-04-23: Previous Chrome install method:
#
#   - name: Fetch Chrome installer
#     get_url:
#       url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
#       dest: "{{ zoidy_homefries_downloads_dir }}/"
#       # checksum: "sha256:{{ <?> }}"
#
#   - name: Install Chrome Debian package
#     become: yes
#     apt:
#       deb: "{{ zoidy_homefries_downloads_dir }}/google-chrome-stable_current_amd64.deb"

