---

- set_fact:
    exiftool_ver: "11.33"

- set_fact:
    exiftool_dir: "Image-ExifTool-{{ exiftool_ver }}"

- set_fact:
    exiftool_pkg: "{{ exiftool_dir }}.tar.gz"

- set_fact:
    exiftool_url: "https://www.sno.phy.queensu.ca/~phil/exiftool/{{ exiftool_pkg }}"

- name: Download Exiftool package
  get_url:
    url: "{{ exiftool_url }}"
    dest: "{{ zoidy_homefries_downloads_dir }}/{{ exiftool_pkg }}"
    # http://owl.phy.queensu.ca/~phil/exiftool/checksums.txt
    checksum: "sha1:a84c8a4d7f97464f6bd9d59ef6fd945c92cee05b"

#- name: Ensure unpack path exists
#  file: path={{ zoidy_homefries_downloads_dir }}/{{ exiftool_dir }} state=directory

- name: Unpack Exiftool package
  unarchive:
    src: "{{ zoidy_homefries_downloads_dir }}/{{ exiftool_pkg }}"
    dest: "{{ zoidy_homefries_downloads_dir }}/"
    remote_src: yes

- name: Build Exiftool application
  command: perl Makefile.PL
  args:
    chdir: "{{ zoidy_homefries_downloads_dir }}/{{ exiftool_dir }}"

- name: Test Exiftool application
  make:
    target: test
    chdir: "{{ zoidy_homefries_downloads_dir }}/{{ exiftool_dir }}"

- name: Install Exiftool application (system-wide)
  become: yes
  make:
    target: install
    chdir: "{{ zoidy_homefries_downloads_dir }}/{{ exiftool_dir }}"

