---

# Very cool localized (directory-specific) environment changes.
#
#   https://github.com/direnv/direnv
#
#   https://direnv.net/
#
# Sort of like an app of mine, gogo
#
#   https://github.com/landonb/pyocalypse-gogo
#
# But more powerful.
#
#   - It runs automatically when you cd into a directory with a .direnv file.
#
#   - It runs before every command. (Or, it wraps every command and runs it
#     from its Go code.)
#
#   - You have to whitelist dirs to indicate that you trust the .direnv therein.
#
# Other apps similar to direnv:
#
#   https://github.com/kennethreitz/autoenv
#
#   https://github.com/sebglazebrook/aliases
#
#   https://github.com/jamesob/desk
#
# Other apps similar to gogo:
#
#   # One could replicate gogo using direnv and bashmarks:
#   https://github.com/huyng/bashmarks
#
# [lb]: 2019-01-02: [go-get] Dependencies that I used to know:
#
#   - "github.com/BurntSushi/toml"
#   - "github.com/direnv/go-dotenv"
#   - "mvdan.cc/sh/cmd/shfmt"
#   - "github.com/cpuguy83/go-md2man"

- name: Clone direnv repo
  git:
    repo: "git@github.com:landonb/direnv.git"
    dest: "{{ zoidy_homefries_downloads_dir }}/direnv"
    # [lb]: 2019-01-02: My working branch fixes an issue...
    version: working

# ***

# E.g., `make`
- name: Build direnv (make)
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
    GOPATH: "{{ ansible_env.HOME }}/.gopath"
  make:
    chdir: "{{ zoidy_homefries_downloads_dir }}/direnv"

# E.g., `DESTDIR=${HOME}/.local make install`
- name: Build direnv (make install)
  make:
    chdir: "{{ zoidy_homefries_downloads_dir }}/direnv"
    target: install
    params:
      DESTDIR: "{{ zoidy_homefries_user_local_dir }}"
    # DESTDIR defaults to: /usr/local
    # DOCS say:
    #   "or symlink ./direnv into the $PATH"
    # but not sure what that means. We need to build the code, right?

