---

- set_fact:
    reptile_keybindings:
      - name: "'Reptile Left'"
        binding: "'<Mod4>Left'"
        action: "'{{ zoidy_homefries_user_local_dir }}/bin/reptile left'"

      - name: "'Reptile Up'"
        binding: "'<Mod4>Up'"
        action: "'{{ zoidy_homefries_user_local_dir }}/bin/reptile top'"

      - name: "'Reptile Right'"
        binding: "'<Mod4>Right'"
        action: "'{{ zoidy_homefries_user_local_dir }}/bin/reptile right'"

      - name: "'Reptile Down'"
        binding: "'<Mod4>Down'"
        action: "'{{ zoidy_homefries_user_local_dir }}/bin/reptile bottom'"

- name: Compute next available custom keybinding
  # [lb]: Not sure why, but pipe is considered illegal character
  #   if it starts a line. At the end of the line, fugetaboutit.
  shell: >
      echo $((
        $(dconf list /org/mate/desktop/keybindings/ |
          sed "s#custom\([0-9]\+\)/#\\1#" |
          sort -n |
          tail -1
        ) + 1 ))
  register: mate_kb_index_cmd
  args:
    executable: /bin/bash

- set_fact:
    mate_kb_index: "{{ mate_kb_index_cmd.stdout | int }}"

- name: reputed-tiler∷ Echo New Keybindings
  debug: msg="{{ item.name }} {{ index + (mate_kb_index | int) }}"
  loop: "{{ reptile_keybindings }}"
  loop_control:
    index_var: index

- name: reputed-tiler∷ Add MATE Key Bindings
  shell: |
    dconf write "/org/mate/desktop/keybindings/custom{{ index + (mate_kb_index | int) }}/name" "{{ item.name }}" ; \
    dconf write "/org/mate/desktop/keybindings/custom{{ index + (mate_kb_index | int) }}/binding" "{{ item.binding }}" ; \
    dconf write "/org/mate/desktop/keybindings/custom{{ index + (mate_kb_index | int) }}/action" "{{ item.action }}" ; \
  loop: "{{ reptile_keybindings }}"
  loop_control:
    index_var: index

