---

- name: "reputed-tiler∷ fetch repo"
  git:
    repo: "ssh://git@github.com/landonb/reputed-tiler.git"
    dest: "{{ zoidy_homefries_downloads_dir }}/reputed-tiler"

- name: "reputed-tiler∷ install app"
  make:
    target: install
    chdir: "{{ zoidy_homefries_downloads_dir }}/reputed-tiler"
  args:
    params:
      PREFIX: "{{ ansible_env.HOME }}/.local"

- name: "reputed-tiler∷ configure keybindings"
  include_role:
    name: zoidy_home-fries
    tasks_from: cli-reptile-keybindings

