---

# USAGE: Task installs Dropbox from apt, and then downloads the daemon.

# ***

# CXREF: https://linux.dropbox.com/packages/ubuntu/
#
#   https://www.dropbox.com/install?os=lnx
#
# - Source archives:
#
#   https://linux.dropbox.com/packages/

# DUNNO/2023-04-25: I was unable to install the Debian package from their
# website, complains:
#   Dependency is not satisfiable: libgtk-4-1 (>= 4.8.0)
# even though I apt-installed libgtk-4-1 (and libgtk-4-dev).
# - Fortunately, you can find packages in the distro repo.

- name: Install Dropbox apt pkgs
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:
    - dropbox
    - caja-dropbox

# - name: Check if Dropbox is running
#   ansible.builtin.command: dropbox status
#   register: dropbox_status
#
# - ansible.builtin.debug: msg={{ dropbox_status.stdout }}

- name: Download Dropbox daemon (answer yes to download prompt)
  ansible.builtin.shell: echo y | DISPLAY='' dropbox start -i

# ***

- name: Tell user to run Dropbox to complete setup
  ansible.builtin.pause:
    seconds: 0
    prompt: |
       

      CHORE » Link your Dropbox account. Run this:

        sensible-open $(dropbox start -i 2> /dev/null | tail -1)"

       
    # ↑ This is an em space ( ), necessary to protect trailing newline(s)
    #   from chomp().
    #   - There's also an em space on the first line, in case you want
    #     first line of content-containing output to be indented.

