---

# *** Local variables (Facts).

- set_fact:
    FONT_URL_ZIPS:
      # 2019-01-03: Skip it: The complete Noto family zip is 1.1G.
      #   And the extracted directory is 1.5G. Get only what's relevant.
      #   - url_base: "https://noto-website-2.storage.googleapis.com/pkgs"
      #     zip_base: "Noto-hinted"
      - url_base: "https://noto-website-2.storage.googleapis.com/pkgs"
        zip_base: "NotoSans-hinted.zip"
      - url_base: "https://noto-website-2.storage.googleapis.com/pkgs"
        zip_base: "NotoSerif-hinted.zip"
      - url_base: "https://noto-website-2.storage.googleapis.com/pkgs"
        zip_base: "NotoSansDisplay-hinted.zip"
      - url_base: "https://noto-website-2.storage.googleapis.com/pkgs"
        zip_base: "NotoSerifDisplay-hinted.zip"
      - url_base: "https://noto-website-2.storage.googleapis.com/pkgs"
        zip_base: "NotoMono-hinted.zip"
      - url_base: "https://noto-website-2.storage.googleapis.com/pkgs"
        zip_base: "NotoSansMono-hinted.zip"
      - url_base: "https://noto-website-2.storage.googleapis.com/pkgs"
        zip_base: "NotoColorEmoji-unhinted.zip"
      - url_base: "https://noto-website-2.storage.googleapis.com/pkgs"
        zip_base: "NotoEmoji-unhinted.zip"

      - url_base: http://dl.1001fonts.com
        zip_base: santos-dumont.zip
      - url_base: http://dl.1001fonts.com
        zip_base: pinewood.zip
      - url_base: http://dl.1001fonts.com
        zip_base: open-sans.zip

- set_fact:
    zip_file_regex: >-
      ^.zip$


# ***

- name: Ensure font download directory exists
  file: path="{{ zoidy_homefries_dls_fonts_dir }}/" state=directory

- name: Ensure destination font directories exist
  file:
    path="{{ ansible_env.HOME }}/.fonts/{{ item.zip_base | regex_replace(zip_file_regex) }}/"
    state=directory
  loop: "{{ FONT_URL_ZIPS }}"

# ***

# PROFILING: 2019-03-19: Task took: 22.51s (currently penutimate slowest task).
- name: Fetch font archives
  get_url:
    url: "{{ item.url_base }}/{{ item.zip_base }}"
    dest: "{{ zoidy_homefries_dls_fonts_dir }}/"
  loop: "{{ FONT_URL_ZIPS }}"

# Copy the archive contents to the ~/.fonts directory, named without the .zip extension.
- name: Unarchive the font archives
  unarchive:
    src: "{{ zoidy_homefries_dls_fonts_dir }}/{{ item.zip_base }}"
    dest: "{{ ansible_env.HOME }}/.fonts/{{ item.zip_base | regex_replace(zip_file_regex) }}/"
    remote_src: yes
  loop: "{{ FONT_URL_ZIPS }}"
  notify: Build font information cache files

