---

# USAGE: Task downloads and installs Hack font from GitHub release archive.

# ***

# CXREF: This task mostly for posterity, superseded by Hack Nerd font.
# - See the zoidy_matecocido Hack Nerd font task:
#   https://github.com/landonb/zoidy_matecocido/blob/release/tasks/font-hack-nerd-font.yml
#     ~/.kit/ansible/roles/zoidy_matecocido/tasks/font-hack-nerd-font.yml
# - Hack font itself (what we'll call "classic") unlikely to ever change versions.
# - Hack Nerd font, on the other hand, is periodically updated.
#   - SPIKE: Describe benefits of Nerd fonts.

# ***

- ansible.builtin.set_fact:
    HACK_VERS_MAJOR: 'v3'
    HACK_VERS_MINOR: '003'

- ansible.builtin.set_fact:
    HACK_VERS: "{{ HACK_VERS_MAJOR }}.{{ HACK_VERS_MINOR }}"

- ansible.builtin.set_fact:
    HACK_FILE: "Hack-{{ HACK_VERS }}-ttf"

# *** Alert user if newer version.

# SAVVY/2023-04-20: `command` is not found by 'command' module,
# because it's a shell construct. I.e., cannot call:
#   ansible.builtin.command: "command -v jq"
- name: 'Test if ‘jq’ is available'
  ansible.builtin.shell: "command -v jq"
  register: is_jq_avail_raw

# Note that this requires sudo/-K if `jq` not installed, but so does the
# 'Build font information cache files' handler, so you're probably running
# this task file with privileges.
- name: 'Ensure ‘jq’ is available'
  become: true
  ansible.builtin.apt: name=jq
  when: is_jq_avail_raw.failed

# SAVVY/2023-04-20 18:39: Still v3.003. (I don't really expect this to ever change.)
- name: Check for new version of Hack.
  ansible.builtin.shell: "curl -s https://api.github.com/repos/source-foundry/Hack/releases/latest | jq -r '.tag_name'"
  register: LATEST_VERSION

- ansible.builtin.debug: msg="Latest HACK∷ {{ LATEST_VERSION.stdout }}"

- ansible.builtin.fail: msg="Update HACK! / Latest∷ {{ LATEST_VERSION.stdout }} / Current∷ {{ HACK_VERS }}"
  when: HACK_VERS != LATEST_VERSION.stdout

# *** Do the work.

- name: Ensure ~/.downloads directory exists
  ansible.builtin.file: path={{ zoidy_homefries_downloads_dir }} state=directory

- name: Fetch the Hack font release, if not previously downloaded
  ansible.builtin.get_url:
    url: "https://github.com/source-foundry/Hack/releases/download/{{ HACK_VERS }}/{{ HACK_FILE }}.zip"
    dest: "{{ zoidy_homefries_downloads_dir }}/"

- name: Ensure user home font directory directory exists
  ansible.builtin.file: path="{{ ansible_env.HOME }}/.fonts/{{ HACK_FILE }}/" state=directory

- name: Unarchive the Hack font release archive (Install Font- HACK!)
  ansible.builtin.unarchive:
    src: "{{ zoidy_homefries_downloads_dir }}/{{ HACK_FILE }}.zip"
    dest: "{{ ansible_env.HOME }}/.fonts/{{ HACK_FILE }}/"
    remote_src: yes
  notify: Build font information cache files

