---

# USAGE: Task installs Go packages using go-install.

# ***

- name: List of Go Lang projects to install
  ansible.builtin.set_fact:
    go_install_list:
      # These projects install to, e.g.,
      #   ~/.gopath/src/{{ item }}

      # 2023-04-22: 8 years stale.
      # - CXREF: https://github.com/jmoiron/jsonq
      #   "simple json field access for golang"
      #
      #  - github.com/jmoiron/jsonq

      # 2023-04-22: I haven't used this is a while.
      # - Added 2017-01-05.
      #
      #  - github.com/landonb/gocovmerge

      # This is somewhat cute. Not sure how useful.
      #
      #  - github.com/jingweno/ccat

      # 2020-01-02: tmux git status line
      # - CXREF: https://github.com/arl/gitmux
      - github.com/arl/gitmux@latest

- name: Install Go Lang projects
  # 2023-04-22: `go get` no longer works. Use go-install.
  #   # Specify "-u"/update to always update projects previously got.
  #   command: "go get -u {{ item }}"
  ansible.builtin.command: "go install {{ item }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
    GOPATH: "{{ ansible_env.HOME }}/.gopath"
  loop: "{{ go_install_list }}"

