---

# USAGE: Task downloads and installs Android Studio from zip release archive.

# ***

# CXREF: https://developer.android.com/studio
#
#   https://developer.android.com/studio#android-studio-downloads
#
# - 2024-02-08: *Android Studio Hedgehog | 2023.1.1 Patch 2 for Linux*
#
#     android-studio-2023.1.1.28-linux.tar.gz
#
#       https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2023.1.1.28/android-studio-2023.1.1.28-linux.tar.gz
#
# - 2023-04-25: *Android Studio Flamingo | 2022.2.1*
#
#     android-studio-2022.2.1.18-linux.tar.gz
#
#       https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2022.2.1.18/android-studio-2022.2.1.18-linux.tar.gz

- ansible.builtin.set_fact:
    # 2024-02-08:
    ANDROID_STUDIO_VER: "2023.1.1.28"
    # CXREF: https://developer.android.com/studio#android-studio-downloads
    ANDROID_STUDIO_SHA: "139d0dbb4909353b68fbf55c09b6d31a34512044a9d4f02ce0f1a9accca128f9"
    # 2023-04-25:
    #  ANDROID_STUDIO_VER: "2022.2.1.18"
    #  ANDROID_STUDIO_SHA: "cdd852c4499b5f7402df44dfc69e8ca418ffc9a684caab34047476fd2cb24efc"
    # 2019-01-05:
    #  ANDROID_STUDIO_VER: "3.2.1.0"
    #  ANDROID_STUDIO_BLD: "181.5056338"
    #  ANDROID_STUDIO_SHA: "b9ec0d44f2feaafe1e3fbd1ed696bf325f9e05cfb6c1ace84dbf87ae249efa84"

- ansible.builtin.set_fact:
    # 2023-04-25:
    ANDROID_STUDIO_NOM: "android-studio-{{ ANDROID_STUDIO_VER }}-linux"
    # 2019-01-05:
    #  ANDROID_STUDIO_NOM: "android-studio-ide-{{ ANDROID_STUDIO_BLD }}-linux"

- ansible.builtin.set_fact:
    # 2023-04-25:
    ANDROID_STUDIO_ARC: "{{ ANDROID_STUDIO_NOM }}.tar.gz"
    # 2019-01-05:
    #  ANDROID_STUDIO_ARC: "{{ ANDROID_STUDIO_NOM }}.zip"

- ansible.builtin.set_fact:
    ANDROID_STUDIO_URI: "https://dl.google.com/dl/android/studio/ide-zips/{{ ANDROID_STUDIO_VER }}/{{ ANDROID_STUDIO_ARC }}"

# ***

# FIXME/2019-01-05: What happens on upgrade? Remove old download?
- name: Stat Android Studio archive file
  ansible.builtin.stat: path="{{ zoidy_homefries_downloads_dir }}/{{ ANDROID_STUDIO_ARC }}"
  register: android_studio_zip_f

# SIZED/2024-02-08: 1.2 GB (2023.1.1.28), but the download should be fast,
# ~23 seconds on my Gigabit fiber connection, using Cat 5e for the LAN.
- name: "Fetch Android Studio release archive"
  ansible.builtin.get_url:
    url: "{{ ANDROID_STUDIO_URI }}"
    dest: "{{ zoidy_homefries_downloads_dir }}/{{ ANDROID_STUDIO_ARC }}"
    checksum: "sha256:{{ ANDROID_STUDIO_SHA }}"
  when: not android_studio_zip_f.stat.exists

# ***

# FIXME/2019-01-05: What happens on upgrade? Remove old directory?
- name: Stat Android Studio unpacked directory
  ansible.builtin.stat: path="{{ zoidy_homefries_downloads_dir }}/android-studio"
  register: android_studio_dir_f

- name: Unarchive the Android Studio release archive
  ansible.builtin.unarchive:
    remote_src: yes
    src: "{{ zoidy_homefries_downloads_dir }}/{{ ANDROID_STUDIO_ARC }}"
    dest: "{{ zoidy_homefries_downloads_dir }}/"
  when: not android_studio_dir_f.stat.exists

# ***

- name: Symlink studio.sh from user bin
  ansible.builtin.file:
    src: "{{ zoidy_homefries_downloads_dir }}/android-studio/bin/studio.sh"
    dest: "{{ ansible_env.HOME }}/.local/bin/studio.sh"
    state: link

