---

# *** Ensure that Go is setup, for other tasks to use/rely upon.

- name: Load role to Install Go Language
  include_role:
    name: zoidy_home-fries
    tasks_from: golang-go-lang
    apply:
      tags:
        - golang-go-lang
        # A number of other tasks rely on Go being available.
        - cli-direnv
        - cli-ripgrep
        - golang-delve-debugger
        - golang-go-get-packages
        # (lb): dubs-vim is from my personal playbook.
        - dubs-vim
  tags:
    - golang-go-lang
    - cli-direnv
    - cli-ripgrep
    - golang-delve-debugger
    - golang-go-get-packages
    - dubs-vim

