---

# https://www.boost.org/users/download/

# https://www.boost.org/doc/libs/1_72_0/more/getting_started/unix-variants.html

# *** Local variables (Facts).

- set_fact:
    # https://www.boost.org/users/history/version_1_74_0.html
    LIBBOOST_DOTVER: '1.74.0'
    LIBBOOST_ULNVER: '1_74_0'

- set_fact:
    LIBBOOST_XSMBZ2: '83bfc1507731a0906e387fc28b7ef5417d591429e51e788417fe9ff025e116b1'

- set_fact:
    LIBBOOST_VERDIR: "boost_{{ LIBBOOST_ULNVER }}"

- set_fact:
    LIBBOOST_TARBZ2: "{{ LIBBOOST_VERDIR }}.tar.bz2"

- set_fact:
    LIBBOOST_REMOTE: "https://dl.bintray.com/boostorg/release/{{ LIBBOOST_DOTVER }}/source/{{ LIBBOOST_TARBZ2 }}"

- set_fact:
    LIBBOOST_PATHBZ: "{{ zoidy_homefries_downloads_dir }}/{{ LIBBOOST_TARBZ2 }}"

# ***

- name: libboost » Fetch
  get_url:
    url: "{{ LIBBOOST_REMOTE }}"
    dest: "{{ LIBBOOST_PATHBZ }}"
    checksum: "sha256:{{ LIBBOOST_XSMBZ2 }}"
  # MAYBE/2020-11-15: Skip if already downloaded (it's 100 MB).
  #  when: False

# ***

- name: libboost » Unpack
  command: "tar --bzip2 -xf {{ LIBBOOST_PATHBZ }}"
  args:
    # NOTE: Unpacks to directory of same name, so can unpack to top-level include.
    chdir: "{{ ansible_env.HOME }}/.local/include"

# MAYBE/2020-11-15: Add step to remove download (it's 100 MB).

