---

- name: List of Node projects to install
  set_fact:
    node_npm_list:
      - mocha
      - parcel-bundler
      - tldr

- name: Ensure nodejs & npm installed
  become: true
  apt: name={{ item }}
  loop:
    # 2020-07-07: `node` installed from latest. See:
    #   node-npmjs-install.yml
    #  - nodejs
    # 2019-12-30: libssl1.0-dev dep. for nodejs-dev.
    - libssl1.0-dev
    # 2019-12-30: nodejs-dev dep. for node-gyp.
    - nodejs-dev
    # 2019-12-30: node-gyp dep. for parcel-bundler.
    - node-gyp
    # 2020-07-07: `npm` installed from latest. See:
    #   node-npmjs-install.yml
    #  - npm

- name: Install Node NPM projects
  npm:
    path: "{{ zoidy_homefries_user_local_dir }}"
    name: "{{ item }}"
  loop: "{{ node_npm_list }}"

# 2018-03-28 12:15: Geolocation of your machine via its IP!
#
# But seems to be wayyyyy off!
#
#   $ whereami # from work wifi
#   42.4645,-83.3763
#
#   $ whereami -f human
#   Michigan, United States
#
# Google Maps puts it at "City of Farmington Hills- Heritage Park",
# outside Detroit... but I'm in Minnesota!
#
# So not really sure the utility of this app!
- name: Install "@rafaelrinaldi/whereami" node.js package globally.
  npm:
    path: "{{ zoidy_homefries_user_local_dir }}"
    name: "@rafaelrinaldi/whereami"

