---

# USAGE: Task downloads and installs multiple Node versions using nvm.

# ***

# CXREF/2023-04-25:
#
#   https://nodejs.org/en/download/releases
#
#   https://nodejs.dev/en/about/releases/

# Rel  Status     Codename  Init Rel    Active LTS  Maint LTS   End Of Life
# V20  Pending              2023-04-18  2023-10-24  2024-10-22  2026-04-30
# V19  Current              2022-10-18              2023-04-01  2023-06-01
# V18  Active LTS Hydrogen  2022-04-19  2022-10-25  2023-10-18  2025-04-30
# V16  Maint LTS  Gallium   2021-04-20  2021-10-26  2022-10-18  2023-09-11
# V14  Maint LTS  Fermium   2020-04-21  2020-10-27  2021-10-19  2023-04-30

# DUNNO/2023-04-25: Linux Mint 21.1 'nodejs' install v12.22.9... which is
# already EOL. Not sure why it didn't include more recent version.

- name: "Install Nodes"
  ansible.builtin.shell: source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install v{{ item }}
  loop:
    # 2023-04-25:
    - 18.16.0
    - 16.20.0
    - 14.21.3
    # 2020-07-07: # Final rel:
    #  - 12.18.2  # 12.22.12
    #             # 10.24.1
    # 2019-01-04:
    #  - 8.9.1    #  8.17.0
    #  - 6.9.4    #  6.17.1
    #             #  4.9.1
    #             #  0.12.18
  args:
    # Run Bash so `source` works.
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"

# For some reason, NVM default to v6.9.4.
#   $ cat ~/.nvm/alias/default
#   v6.9.4
# 2020-07-07: On my laptop, default is 'system':
#     $ cat ~/.nvm/alias/default
#     system
#   and I added node-npm-packages.yml which installs latest, 12.18.2,
#   but requires that PATH reflect that... so not exactly system node,
#   more like my user's node.
- name: "Set Default Node.js"
  ansible.builtin.shell: source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm alias default system
  args:
    # Run Bash so `source` works.
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"

