---

- set_fact:
    NODE_INSTALL_SH_VER: "v0.33.11"

- set_fact:
    NODE_INSTALL_SH_URI: "https://raw.githubusercontent.com/creationix/nvm/{{ NODE_INSTALL_SH_VER }}/install.sh"
    NODE_INSTALL_SCRIPT: "nvm-{{ NODE_INSTALL_SH_VER }}-install.sh"

- name: Ensure ~/.downloads/nvm-* directory exists
  file: "path={{ zoidy_homefries_downloads_dir }}/nvm-{{ NODE_INSTALL_SH_VER }} state=directory"

- name: Fetch nvm install script
  get_url:
    url: "{{ NODE_INSTALL_SH_URI }}"
    dest: "{{ zoidy_homefries_downloads_dir }}/nvm-{{ NODE_INSTALL_SH_VER }}/{{ NODE_INSTALL_SCRIPT }}"
    mode: 0755

# FIXME/2019-01-04: How best to verify script before blindly running it??
#- fail: msg=XXX

- name: Run nvm install script
  command: "./{{ NODE_INSTALL_SCRIPT }}"
  args:
    chdir: "{{ zoidy_homefries_downloads_dir }}/nvm-{{ NODE_INSTALL_SH_VER }}"

