---

- name: Load pip_list
  include_role:
    name: zoidy_apps_et_al
    tasks_from: python-pip-pkg-list
    apply:
      tags:
        - python-pip-pkg-list
  tags: python-pip-pkg-list

- name: Install User Pip3 packages
  #pip:
  #  name: "{{ pip_list }}"
  #  executable: /usr/bin/pip3
  #  extra_args: --user --upgrade
  command: "/usr/bin/pip3 install --user --upgrade {{ item }}"
  loop: "{{ pip_list }}"

