---

- name: List Python Sources to Download
  set_fact:
    python_versions:
      - 2.7.17  # 2019-10-19
      - 3.3.7   # 2017-09-19
      - 3.4.10  # 2019-03-18
      - 3.5.8   # 2019-10-29
      - 3.6.10  # 2019-12-18
      - 3.7.6   # 2019-12-18
      - 3.8.1   # 2019-12-18

- set_fact:
    zoidy_homefries_dls_pydls_dir: "{{ zoidy_homefries_downloads_dir }}/python-dls"
    zoidy_homefries_dls_pysrc_dir: "{{ zoidy_homefries_downloads_dir }}/python-src"

# ***

- name: Ensure Python sources download directory exists
  file: path="{{ zoidy_homefries_dls_pydls_dir }}" state=directory

- name: Ensure Python sources unpack directory exists
  file: path="{{ zoidy_homefries_dls_pysrc_dir }}" state=directory

# ***

- name: Fetch Python source archives
  get_url:
    url: "https://www.python.org/ftp/python/{{ item }}/Python-{{ item }}.tar.xz"
    dest: "{{ zoidy_homefries_dls_pydls_dir }}/"
  loop: "{{ python_versions }}"

- name: Unarchive the Python source archives
  unarchive:
    src: "{{ zoidy_homefries_dls_pydls_dir }}/Python-{{ item }}.tar.xz"
    dest: "{{ zoidy_homefries_dls_pysrc_dir }}/"
    remote_src: yes
  loop: "{{ python_versions }}"

