---

- name: Run pip3 installer
  include_role:
    name: zoidy_home-fries
    tasks_from: python-pip-pip3-user
    apply:
      tags:
        - python-pip-pip3-user
  tags: python-pip-pip3-user

- name: Run pip2 installer
  include_role:
    name: zoidy_home-fries
    tasks_from: python-pip-pip2-user
    apply:
      tags:
        - python-pip-pip2-user
  tags: python-pip-pip2-user

- name: Activate argcomplete bash tab completion
  command: "{{ zoidy_homefries_user_local_dir }}/bin/activate-global-python-argcomplete --user"

