---

# https://www.ivpn.net/setup/gnu-linux-terminal.html

- name: Choose location configs to Install
  set_fact:
    ivpn_locations:
      - Germany.ovpn
      - USA-Chicago.ovpn

- name: Install OpenVPN and related packages
  become: true
  apt: name={{ item }}
  loop:
    - openvpn
    - openresolv

- name: Download the OpenVPN config files
  get_url:
    url: "https://www.ivpn.net/releases/config/ivpn-openvpn-config.zip"
    dest: "{{ zoidy_homefries_downloads_dir }}/ivpn-openvpn-config.zip"

# - name: Ensure OpenVPN config files unarchive target directory exists
#   file: path="{{ zoidy_homefries_downloads_dir }}/ivpn-openvpn-config" state=directory

- name: Unarchive the OpenVPN config files
  unarchive:
    src: "{{ zoidy_homefries_downloads_dir }}/ivpn-openvpn-config.zip"
    # dest: "{{ zoidy_homefries_downloads_dir }}/ivpn-openvpn-config"
    dest: "{{ zoidy_homefries_downloads_dir }}"
    remote_src: yes

- name: Create OpenVPN credentials file
  become: yes
  template:
    src: ../templates/etc-openvpn-pass.j2
    dest: "/etc/openvpn/pass"
    mode: 0400
  when: |
    zoidy_homefries_openvpn_user != ""
    and zoidy_homefries_openvpn_pass != ""

- name: Copy IPVN OpenVPN configuration file(s)
  become: yes
  copy:
    src: "{{ zoidy_homefries_downloads_dir }}/ivpn-openvpn-config/{{ item }}"
    dest: "/etc/openvpn/{{ item }}"
    remote_src: yes
    mode: 0664
  with_items: "{{ ivpn_locations }}"

- name: Edit OpenVPN config to use the password file
  become: yes
  lineinfile:
    path: "/etc/openvpn/{{ item }}"
    regexp: '^auth-user-pass'
    line: "auth-user-pass pass"
  with_items: "{{ ivpn_locations }}"

- name: Edit OpenVPN config to use IVPN DNS servers (1 / 3)
  become: yes
  lineinfile:
    path: "/etc/openvpn/{{ item }}"
    regexp: '^script-security '
    line: "script-security 2"
  with_items: "{{ ivpn_locations }}"

- name: Edit OpenVPN config to use IVPN DNS servers (2 / 3)
  become: yes
  lineinfile:
    path: "/etc/openvpn/{{ item }}"
    regexp: '^up '
    line: "up /etc/openvpn/update-resolv-conf"
  with_items: "{{ ivpn_locations }}"

- name: Edit OpenVPN config to use IVPN DNS servers (3 / 3)
  become: yes
  lineinfile:
    path: "/etc/openvpn/{{ item }}"
    regexp: '^down '
    line: "down /etc/openvpn/update-resolv-conf"
  with_items: "{{ ivpn_locations }}"

