---

# USAGE: Task builds and installs ttygif from GitHub sources.

# ***

- name: Install ttygif prerequisites
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:
    - imagemagick
    - ttyrec
    - gcc
    - x11-apps

- name: Clone ttygif repo
  ansible.builtin.git:
    repo: "git@github.com:icholy/ttygif.git"
    dest: "{{ zoidy_homefries_downloads_dir }}/ttygif"

- name: Build ttygif
  ansible.builtin.make:
    chdir: "{{ zoidy_homefries_downloads_dir }}/ttygif"

- name: Install ttygif
  ansible.builtin.make:
    chdir: "{{ zoidy_homefries_downloads_dir }}/ttygif"
    target: install
  args:
    params:
      PREFIX: "{{ ansible_env.HOME }}/.local"

