---

# USAGE: Task downloads and installs vagrant from deb package.

# ***

# CXREF: https://releases.hashicorp.com/vagrant

- set_fact:
    # 2019-01-05:
    #  vagrant_ver: "2.2.2"
    # 2023-04-25:
    # - CXREF: https://releases.hashicorp.com/vagrant/2.3.4/
    vagrant_ver: "2.3.4"

- set_fact:
    hashicorp_com_sha: "vagrant_{{ vagrant_ver }}_SHA256SUMS"
    hashicorp_com_sig: "vagrant_{{ vagrant_ver }}_SHA256SUMS.sig"
    # 2019-01-05:
    #  vargrant_deb: "vagrant_{{ vagrant_ver }}_x86_64.deb"
    # 2023-04-25:
    vargrant_deb: "vagrant_{{ vagrant_ver }}-1_amd64.deb"

# E.g., https://releases.hashicorp.com/vagrant/2.3.4/vagrant_2.3.4-1_amd64.deb
- set_fact:
    vagrant_url: "https://releases.hashicorp.com/vagrant/{{ vagrant_ver }}/{{ vargrant_deb }}"

- name: Download Hashicorp.com SHA list
  get_url:
    url: "https://releases.hashicorp.com/vagrant/{{ vagrant_ver }}/{{ hashicorp_com_sha }}"
    dest: "{{ zoidy_homefries_downloads_dir }}/{{ hashicorp_com_sha }}"

- name: Download Hashicorp.com Signature
  get_url:
    url: "https://releases.hashicorp.com/vagrant/{{ vagrant_ver }}/{{ hashicorp_com_sig }}"
    dest: "{{ zoidy_homefries_downloads_dir }}/{{ hashicorp_com_sig }}"

- name: Download Vagrant package
  get_url:
    url: "{{ vagrant_url }}"
    dest: "{{ zoidy_homefries_downloads_dir }}/{{ vargrant_deb }}"
    # 2019-01-05:
    #  # https://releases.hashicorp.com/vagrant/2.2.2/vagrant_2.2.2_SHA256SUMS
    #  checksum: "sha256:4dec711612c4350733e01745ab9f5acee2fbf9756ab9728b19a4664cae5c275d"
    # 2023-04-25:
    # https://releases.hashicorp.com/vagrant/2.3.4/vagrant_2.3.4_SHA256SUMS
    checksum: "sha256:d86a174063eea4376d71f7e5e34cd1e9c2be1e71c8f3ba64e70f2fac9f53c85c"

- name: Install Vagrant package
  become: yes
  ansible.builtin.apt:
    deb: "{{ zoidy_homefries_downloads_dir }}/{{ vargrant_deb }}"

