---

# [lb]: On 14.04 and 16.04, I found xrandr-invert-colors to be fairly reliable
# (ever so often, the invert wouldn't happen, so I'd have to repeat the command).
# I had at some point installed and tested `xcalib`, but for whatever reason, it
# didn't stick. The xcalib equivalent to `xrandr-invert-colors` is probably:
#
#   xcalib -invert -alter
#
# In any case, I'm running 18.04 now, mostly on a new T480, and it remains to be
# seen how well xrandr-invert-colors will perform. (For reference, I use the tool
# as a way to alert me when a locally running, automatically invoked Continuous
# Integrataion script completes.)

# Restore changes! (See lineinfile's, below.)
- name: Restore repo changes
  shell: /usr/bin/git checkout -- Makefile
  args:
    chdir: "{{ zoidy_homefries_downloads_dir }}/xrandr-invert-colors"

- name: Clone xrandr-invert-colors repo
  git:
    repo: "ssh://git@github.com/zoltanp/xrandr-invert-colors.git"
    dest: "{{ zoidy_homefries_downloads_dir }}/xrandr-invert-colors"

# E.g., `sudo make deps-apt`
- name: 'Install xrandr-invert-colors dependencies'
  become: true
  # Essentially same as:
  #   apt: name=libxcb-randr0-dev
  make:
    chdir: "{{ zoidy_homefries_downloads_dir }}/xrandr-invert-colors"
    target: deps-apt
  # DEVs: Uncomment to be able to run task without -K password prompt.
  #  when: False

# E.g., `make clean`
- name: Clean xrandr-invert-colors build
  make:
    chdir: "{{ zoidy_homefries_downloads_dir }}/xrandr-invert-colors"
    target: clean

# E.g., `make`
- name: Build xrandr-invert-colors
  make:
    chdir: "{{ zoidy_homefries_downloads_dir }}/xrandr-invert-colors"

# Install locally to user, bruh.
- name: Fix xrandr-invert-colors Makefile, Part 1
  lineinfile:
    path: "{{ zoidy_homefries_downloads_dir }}/xrandr-invert-colors/Makefile"
    # Was:
    #   PREFIX=/usr/local
    regexp: '^PREFIX='
    line: "PREFIX={{ ansible_env.HOME }}/.local"

# [lb]: This is ridonkulous. I should either just install as root, or fork the project.
- name: Fix xrandr-invert-colors Makefile, Part 2
  lineinfile:
    path: "{{ zoidy_homefries_downloads_dir }}/xrandr-invert-colors/Makefile"
    # Remove root:root assignment.
    #   -v/--verbose, -s/--strip symbol tables, -p/--preserve-timestamps, --mode
    regexp: '^(.*)install -v -s -p -m 755 -o root -g root(.*)$'
    line: '\1install -v -s -p -m 755\2'
    # Enable backrefs for \1, etc., to be recognized.
    backrefs: yes

# E.g., `make install`
- name: Install xrandr-invert-colors
  make:
    chdir: "{{ zoidy_homefries_downloads_dir }}/xrandr-invert-colors"
    target: install
    # Ideally, we could set PREFIX from without, e.g.,:
    #   params:
    #     PREFIX: "{{ ansible_env.HOME }}/.local"
    # but the Makefile currently hardcodes paths.

# Restore changes!
- name: Restore xrandr-invert-colors repo changes, so next clone/pull works
  shell: /usr/bin/git checkout -- Makefile
  args:
    chdir: "{{ zoidy_homefries_downloads_dir }}/xrandr-invert-colors"

