---
# handlers file for zoidy_home-fries

- name: Build font information cache files
  become: yes
  shell: "fc-cache -fv"

# E.g., `sudo systemctl restart postfix`.
- name: Restart Postfix
  become: yes
  systemd:
    name: postfix
    state: restarted
    enabled: yes

